### ISSUE TITLE
[BUG] ImportError: cannot import name 'escape' from 'jinja2' (C:\Users\LT\AppData\Roaming\Python\Python39\site-packages\jinja2\__init__.py)

### ISSUE THREAD

**Issue by TalalAhmed311** [mlflow/mlflow#7621] opened 2022-12-29 10:43 UTC
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

2.1.1

### System information

- **Windows 10 Pro 64-bit**:
- **Python 3.9.13**:

### Describe the problem

I try to run the ui, by simply writing mlflow ui in Pyrcharm terminal and also try this in jupyter notebook but this jinja2 error come anyway. 
Some steps already taken to solving the bug.

Uninstall and re-install packages:
Flask
Jinja2
mlflow 

### Steps to reproduce the bug

Here is the directory structure

![image](https://user-images.githubusercontent.com/64472176/209940073-2901b592-7eb7-43dc-85de-ce6f1e820997.png)

Error Message:

![image](https://user-images.githubusercontent.com/64472176/209940177-6083b245-1733-4620-b960-cbd9b38f5d3d.png)

**Comment by harupy** [comment] 2023-01-05 05:27
A duplicate of https://github.com/mlflow/mlflow/issues/7563

**Closed by harupy** 2023-01-05 05:27 UTC
Labels: bug, area/uiux
