### ISSUE TITLE
[BUG] MLFLOW_S3_ENDPOINT_URL  is ignored

### ISSUE THREAD

**Issue by tamis-laan** [mlflow/mlflow#7104] opened 2022-10-19 14:38 UTC
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

mlflow, version 1.29.0

### System information

- Arch Linux
- Python 3.10.8

### Describe the problem

I'm trying to start the mlflow tracking server with an bucket and a postgresql database attached. The object store is not hosted by AWS but implements the S3 api interface. 

When adding an artifact to the database mflow throws an error that it cannot connect to the bucket. It complains about not being able to connect to AWS.

I have set all the nesessary environment variables.

### Tracking information

No notebook

### Code to reproduce issue

```
MLFLOW_TRACKING_URI=http://0.0.0.0:5000
MLFLOW_BACKEND_STORE_URI=postgresql://<user>:<password>@<host>:<port>
MLFLOW_S3_ENDPOINT_URL=https://<edacted>.<redacted>.cloud
AWS_ACCESS_KEY_ID=<redacted>
AWS_SECRET_ACCESS_KEY=<redacted>
```

```
mlflow server --default-artifact-root s3://mlflow/ --host 0.0.0.0
```

### Stack trace

```
Traceback (most recent call last):
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/httpsession.py", line 455, in send
    urllib_response = conn.urlopen(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x7f9e5b7b9e70>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/mlflow/server/handlers.py", line 456, in wrapper
    return func(*args, **kwargs)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/mlflow/server/handlers.py", line 526, in wrapper
    return func(*args, **kwargs)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/mlflow/server/handlers.py", line 909, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 159, in list_artifacts
    for result in results:
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "$HOME/.local/share/virtualenvs/ai-panoptes-O4NUaGdJ/lib/python3.10/site-packages/botocore/httpsession.py", line 484, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.nl-ams.amazonaws.com/mlflow?list-type=2&prefix=1%2F6c3af048e4a74ded9dd43ddd898c0d3c%2Fartifacts%2F&delimiter=%2F&encoding-type=url"
```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment] 2022-10-19 14:48
@tamis-laan Can you access the bucket using boto3?

**Comment by harupy** [comment] 2022-10-24 01:19
@tamis-laan Any updates?

**Comment by harupy** [comment] 2022-10-24 07:12
@tamis-laan Can you run this code?

```python
# Save this code as a.py

import os
import mlflow

assert "MLFLOW_S3_ENDPOINT_URL" in os.environ
assert "AWS_ACCESS_KEY_ID" in os.environ
assert "AWS_ACCESS_KEY_ID" in os.environ


with mlflow.start_run():
    mlflow.log_artifact(__file__)
```

**Comment by tamis-laan** [comment] 2022-10-24 09:32
@harupy I need to finish some work and then I will get back to this issue.

**Comment by tamis-laan** [comment] 2022-10-24 14:40
> @tamis-laan Can you run this code?
> 
> ```python
> # Save this code as a.py
> 
> import os
> import mlflow
> 
> assert "MLFLOW_S3_ENDPOINT_URL" in os.environ
> assert "AWS_ACCESS_KEY_ID" in os.environ
> assert "AWS_SECRET_ACCESS_KEY" in os.environ
> 
> 
> with mlflow.start_run():
>     mlflow.log_artifact(__file__)
> ```
> 
> Did you set `MLFLOW_S3_ENDPOINT_URL` when running your client code?

Nope it connects to the tracking server and then throws the same error:
```
  File "/home/tux/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/tux/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/httpsession.py", line 484, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "https://s3.nl-ams.amazonaws.com/mlflow/0/fdd9829327504b1594347025d7807cdd/artifacts/test.py"
```

**Comment by harupy** [comment] 2022-10-24 14:44
@tamis-laan Got it, can you access the bucket with boto3?

**Comment by tamis-laan** [comment] 2022-10-24 18:02
Using boto3 I can connect to the object storage:

```
MLFLOW_TRACKING_URI=http://0.0.0.0:8000
MLFLOW_BACKEND_STORE_URI=postgresql://<user>:<pass>@<ip>:<port>/mlflow
MLFLOW_ARTIFACTS_DESTINATION=s3://mflow
MLFLOW_DEFAULT_ARTIFACT_ROOT=https://models.xxx.xxx.xxx.cloud/
MLFLOW_S3_ENDPOINT_URL=https://models.xxx.xxx.xxxx.cloud/
AWS_ACCESS_KEY_ID=xxxxxxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxx
```

``` python
import boto3
import os

session = boto3.session.Session()

s3_client = session.client(
    service_name='s3',
    aws_access_key_id=os.getenv('AWS_ACCESS_KEY_ID'),
    aws_secret_access_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
    endpoint_url=os.getenv('MLFLOW_DEFAULT_ARTIFACT_ROOT'),
    region_name=os.getenv('AWS_DEFAULT_REGION')
)

print(s3_client.list_buckets())
```

But running the server results in:
```
 2022/10/24 19:56:51 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/server/handlers.py", line 455, in wrapper
    return func(*args, **kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/server/handlers.py", line 525, in wrapper
    return func(*args, **kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/server/handlers.py", line 914, in _list_artifacts
    artifact_entities = _get_artifact_repo(run).list_artifacts(path)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 159, in list_artifacts
    for result in results:
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.
```

**Comment by harupy** [comment] 2022-10-24 22:18
@tamis-laan The traceback says "the specified key does not exist". Are you sure the artifact URI is correct?

**Comment by zingbert** [comment] 2022-10-25 07:50
Don't know if this could help, I've had a similar issue with remote tracking (with mlflow==1.29.0 and mlflow==1.30.0) of artifacts on Digital Ocean Spaces compatible S3 and **resolved** with this [harupy comment](https://github.com/mlflow/mlflow/issues/7104#issuecomment-1288522699), before I wasn't setting MLFLOW_S3_ENDPOINT_URL=https://<region-name>.digitaloceanspaces.com (https://github.com/mlflow/mlflow/issues/5439) also on the client side (only S3 credentials) and I was getting an error like:

`Could not connect to the endpoint URL: "https://<bucket-name>.s3.<region-name>.amazonaws.com/5/190cbf0a10734f308d070059f0dd8698/artifacts/model/model.pkl"`

from a `mlflow.sklearn.log_model` on a simple jupyter lab on the mlflow _sklearn_logistic_regression_ example,
so there was clearly a malformed url instead of the correct one `https://<bucket-name>.<region-name>.digitaloceanspaces.com`.

IMHO this issue clashes with the [official documentation](https://mlflow.org/docs/latest/tracking.html#amazon-s3-and-s3-compatible-storage) when a a **warning box** says:

> ... For example, providing --default-artifact-root $MLFLOW_S3_ENDPOINT_URL on the server side **and** MLFLOW_S3_ENDPOINT_URL on the client side will create a **client path resolution issue for the artifact storage location** ... 

continuing with

> ... To prevent path parsing issues, **ensure** that reserved environment variables are **removed (unset)** from client environments. 

Actually **the opposite is true**, so now if this is the intended way to make S3 compatbile storage working for remote artifact storage maybe the official documentation has be updated.

**Comment by tamis-laan** [comment] 2022-10-25 08:36
I'm a bit confused when it comes to the settings and selecting the right bucket. Let me know if this is correct:

I authenticate and connect to the s3 object store as followed:
```
AWS_DEFAULT_REGION=xxxx
MLFLOW_S3_ENDPOINT_URL=https://xxx.xxx.xxx.xxx.cloud
AWS_ACCESS_KEY_ID=xxxx
AWS_SECRET_ACCESS_KEY=xxx
```

Then I need to select the bucket I named mlflow to use to store artifacts:
```
MLFLOW_DEFAULT_ARTIFACT_ROOT=s3://mlflow
MLFLOW_ARTIFACTS_DESTINATION=s3://mflow
```

Given the error:
```
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.
```
It looks like it can connect to the object store but fails to list the objects in the bucket? Let me know if I miss-configured things.

**Comment by harupy** [comment] 2022-10-25 10:55
@tamis-laan 

```python
import mlflow

mlflow.MlflowClient().list_artifacts(<run_id>, ".")
```

Can you list artifacts using this code?

**Comment by tamis-laan** [comment] 2022-10-25 10:58
> @tamis-laan
> 
> ```python
> import mlflow
> 
> mlflow.MlflowClient().list_artifacts(<run_id>)
> ```
> 
> Can you list artifacts using this code?

I changed my original comment above

**Comment by harupy** [comment] 2022-10-25 11:02
Did you set the credentials when running the client code?

**Comment by tamis-laan** [comment] 2022-10-25 11:15
> Did you set the credentials when running the client code? By default, the client doesn't communicate with the server when uploading/downloading artifacts. As the traceback indicates, the client directly uses boto3 and doesn't send any requests to the server.

No I havn't set any s3 credentials for the client, I'm trying to run all communications through the tracking server as shown in scenario 5:
https://www.mlflow.org/docs/latest/_images/scenario_5.png

**Comment by harupy** [comment] 2022-10-25 11:22
Ok, can you try running this code?

```python
import mlflow
import uuid

mlflow.set_experiment(uuid.uuid4().hex)

with mlflow.start_run():
    mlflow.log_artifact(__file__)
```

**Comment by harupy** [comment] 2022-10-25 11:40
Can you open `/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 159` and insert a print function? 

```diff
        (bucket, artifact_path) = data.parse_s3_uri(self.artifact_uri)
        dest_path = artifact_path
        if path:
            dest_path = posixpath.join(dest_path, path)
        infos = []
        prefix = dest_path + "/" if dest_path else ""
        s3_client = self._get_s3_client()
        paginator = s3_client.get_paginator("list_objects_v2")
+       print(bucket, prefix)
        results = paginator.paginate(Bucket=bucket, Prefix=prefix, Delimiter="/")
        for result in results:
```

**Comment by tamis-laan** [comment] 2022-10-25 11:48
> ```diff
> print(bucket, artifact_path, prefix)
> ```


```
Loading .env environment variables...
[2022-10-25 13:45:06 +0200] [97525] [INFO] Starting gunicorn 20.1.0
[2022-10-25 13:45:06 +0200] [97525] [INFO] Listening at: http://0.0.0.0:8000 (97525)
[2022-10-25 13:45:06 +0200] [97525] [INFO] Using worker: sync
[2022-10-25 13:45:06 +0200] [97526] [INFO] Booting worker with pid: 97526
[2022-10-25 13:45:06 +0200] [97527] [INFO] Booting worker with pid: 97527
[2022-10-25 13:45:06 +0200] [97528] [INFO] Booting worker with pid: 97528
[2022-10-25 13:45:06 +0200] [97529] [INFO] Booting worker with pid: 97529
[2022-10-25 13:45:07 +0200] [97525] [INFO] Handling signal: winch
[2022-10-25 13:45:09 +0200] [97525] [INFO] Handling signal: winch
[2022-10-25 13:45:10 +0200] [97525] [INFO] Handling signal: winch
[2022-10-25 13:45:24 +0200] [97525] [INFO] Handling signal: winch
mlflow  3/102e887fbc81495ba43537f1692185c1/artifacts/
2022/10/25 13:45:59 ERROR mlflow.server: Exception on /ajax-api/2.0/preview/mlflow/artifacts/list [GET]
Traceback (most recent call last):
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/server/handlers.py", line 455, in wrapper
    return func(*args, **kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/server/handlers.py", line 525, in wrapper
    return func(*args, **kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/server/handlers.py", line 909, in _list_artifacts
    artifact_entities = _list_artifacts_for_proxied_run_artifact_root(
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/server/handlers.py", line 455, in wrapper
    return func(*args, **kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/server/handlers.py", line 946, in _list_artifacts_for_proxied_run_artifact_root
    for file_info in artifact_destination_repo.list_artifacts(artifact_destination_path):
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/mlflow/store/artifact/s3_artifact_repo.py", line 160, in list_artifacts
    for result in results:
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/$HOME/.local/share/virtualenvs/ai-mlflow-server-jL1b2NAi/lib/python3.10/site-packages/botocore/client.py", line 938, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.
[2022-10-25 13:46:03 +0200] [97525] [INFO] Handling signal: winch
```

BTW I send you a google meet invitation through gmail if you want to debug this isue in real time.

**Comment by harupy** [comment] 2022-10-25 23:56
Fixed by the following changes:

1. Fix the bucket name and endpoint URL.
2. Remove `MLFLOW_DEFAULT_ARTIFACT_ROOT` in the client environment.

**Closed by harupy** 2022-10-25 23:56 UTC
Labels: bug, area/artifacts

**Comment by MingStar** [comment] 2023-02-07 03:31
While the mlflow client seems to be getting the `--default-artifact-root` setting from the tracking server, maybe it SHOULD also get the values of `MLFLOW_S3_ENDPOINT_URL` and `MLFLOW_S3_IGNORE_TLS` from the server IF they're set on the server side? it will make the remote server setup easier by consolidating the environment variables

**Comment by iamhritik290799** [comment] 2024-03-01 18:34
@harupy can you please help me what will be the correct value for the below args and ENV Variable:
if I'm storing my artifacts in this location - s3://dataengineering-mlflow-bucket/mlflow/artifacts/

```
--default-artifact-root = ?
--artifacts-destination= ?

MLFLOW_S3_ENDPOINT_URL : ?
```
