### ISSUE TITLE
[BUG] Missing optional dependecies in requirements.txt

### ISSUE THREAD

**Issue by sxooler** [mlflow/mlflow#10684] opened 2023-12-13 15:35 UTC
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.1.1
- Tracking server: 2.1.1

### System information

- **OS Platform and Distribution**: Ubuntu 20.04 (WSL2)
- **Python version**: 3.10.13

### Describe the problem

I am running my script using similar command:
```
mlflow run git@gitlab.com:custom-repo.git#scripts/pv_model -e main -P parameter1=test --experiment-name test-model
```

Content of `MLproject`:
```
name: model_example

python_env: python_env.yaml

entry_points:
    ... # list of entry points
```

and content of `python_env.yaml`:
```
python: "3.10"
build_dependencies:
  - pip
dependencies:
  - mlflow==2.1.1
  - custom-lib[models]
```

All the training works fine, model is logged with all other stuff (including parameters, metrics, dependencies). The issue is that content of `requirements.txt` (same applies to `conda.yaml`) looks like this:
```
mlflow<3,>=2.1
cloudpickle==2.2.1
custom-lib==1.0.26
```
where optional dependencies/extras (**models**) are missing. This basically means that no one can install all models dependencies from such `requirements.txt` as those extras deps will be missing.

Is there some workaround or proper way how to deal with such extras dependencies or is it rather a bug that should be fixed?

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

Run `mlflow run` with `MLproject` pointing to `python_env.yaml` with a required optional dependencies like `custom-lib[extras]`.

### Stack trace

No stack trace (command runs correctly).

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment] 2023-12-14 07:53
Hi @sxooler! It's a little tricky to infer whether an extra is required for a model, but if you want to ensure that the extra is included in the `requirements.txt` file, you can use the `extra_pip_requirements` param when saving your model. Here's an example (you can also refer to [this page in the docs](https://mlflow.org/docs/latest/deployment/deploy-model-to-kubernetes/index.html#specifying-pip-requirements-using-pip-requirements-and-extra-pip-requirements) for more examples):

```python
import mlflow

class MyModel(mlflow.pyfunc.PythonModel):
    def predict(self, context, model_input):
        return model_input
    
mlflow.pyfunc.save_model(
    path="my-model", 
    python_model=MyModel(),
    extra_pip_requirements=["scikit-learn[openmp]"]
)
```

The `requirements.txt` file should have the package and extra listed:
```
mlflow==2.9.1
cloudpickle==2.2.1
scikit-learn[openmp]
```

Let me know if this solves your problem!

**Comment by sxooler** [comment] 2023-12-14 15:38
@daniellok-db thank you for your reply. I was not aware of this functionality (using `extra_pip_requirements`), so that's definitely useful, thank you! I have a few follow-up questions.

1. I was not able to make it work in my custom project, but it's a bit more complex one so I will try to find a way to make it work or submit another issue if I find a way how to reproduce it.

2. I was able to reproduce it with a simple project. But there are several issues:
- library version is not listed (as in your example, there is only `scikit-learn[openmp]` in the final `requirements.txt`, no version info)
- (I could provide version directly in `extra_pip_requirements`, I guess, but that would mean I need to update it every time when new lib is released, but my idea was that the latest lib version would be taken during training, logged and then re-used when deploying the trained model)
- should I keep it (e.g. `scikit-learn[openmp]`) in my `python_env.yaml` as well or only as `extra_pip_requirements`?

3. Which leads to another question - how to properly handle `python_env.yaml` and `extra_pip_requirements`? I understand it might be kind of tricky to correctly infer all the requirements including extras, but having a single place/file where I can put my dependencies (which was `python_env.yaml` in my case) is much easier to handle than adding another requirements directly in the code (and I usually have sth like multi-step workflow, therefore several steps share the same MLproject with its dependencies).

**Comment by daniellok-db** [comment] 2023-12-15 03:41
No worries glad it was helpful! For your follow up questions:

2. If you want to pin whatever version you have installed when saving your model, you can do it like this:
```python
mlflow.pyfunc.save_model(
  ...
  extra_pip_requirements=[f"custom_lib[models]=={custom_lib.__version__}"]
)
```
You can keep `custom_lib[models]` in your `python_env.yaml` as well, there shouldn't be any issues with this.

3. I think this question depends on your workflow. Conceptually, the `requirements.txt` file saved with the model just contains all the dependencies required to load and perform inference with the model. The `python_env.yaml` file associated with your MLproject file is for dependencies requires for your broader project (which may be more extensive than what your model requires for inference).

Hope this helps!

**Comment by sxooler** [comment] 2023-12-15 14:18
Great, this makes sense. To clarify one thing - do I understand it correctly that `python_env.yaml` is used as a source for project creation (including creating `venv` and installing listed packages) when running `mlflow run ...` and then when model is logged mlflow somehow decides which packages will go to `requirements.txt`?

I was confused several times about the content of the logged `requirements.txt` and the difference to `python_env.yaml` used in my workflow. Your explanation sheds some light on my confusion :) But I am still trying to understand what is going on under the hood. Do you have some reference on this topic (more details and so on)?

It seems to me that I should use `python_env.yaml` to provide dependencies to my workflow (all steps, not just inference) and if I cannot (or don't want to) rely on default handling of `requirements.txt` (that is somehow done by mlflow based on the provided dependencies and logged model afaik based on our conversation) I should rather provide my own requirements for inference (using `pip_requirements` and `extra_pip_requirements`). Is that correct?

**Comment by daniellok-db** [comment] 2023-12-17 04:25
Yup, you got it! If you're interested in the technical details of how we infer the requirements of a model, you can take a look at the [`infer_pip_requirements` function in the code](https://github.com/mlflow/mlflow/blob/51dd444ffb466ff5fce86b2024563d062f12c2e5/mlflow/utils/environment.py#L383). When you call `save_model()`, eventually this function gets called to infer the requirements of just the model.

I'll close the issue now since it seems more or less resolved, but feel free to let me know if you have anything else you want to know.

**Comment by sxooler** [comment] 2023-12-20 12:10
@daniellok-db I have one follow-up question - in some case package requirements are logged twice. E.g. in `python_env.yaml`, there is `mypkg[models]==1.0.1` (required for model trying and other parts of the pipeline to run) and I put `extra_pip_requirements=["mypkg[models]==1.0.1"]` to ensure it will get correctly logged as model requirements including extras. Then in `requirements.txt` of the logged model I can find following two lines:
```
mypkg==1.0.1
mypkg[models]==1.0.1
```
You said
> You can keep custom_lib[models] in your python_env.yaml as well, there shouldn't be any issues with this.

But is the described behavior expected? Because it gets logged twice (one without extras inferred by mlflow and one with extras because of used `extra_pip_requirements`).

**Comment by daniellok-db** [comment] 2023-12-20 13:03
Ah this may be a bug, I would expect that if a package is provided in extra_pip_requirements, and it's already in the inferred requirements, it should overwrite it. I'll check and get back to you!

**Comment by daniellok-db** [comment] 2023-12-22 01:30
Confirmed that the extras should override the main package. I'll follow up with a fix, but probably only going to be able to get to it in a couple of weeks. Thank you for the report!

**Closed** 2024-01-05 21:23 UTC
Labels: bug, area/artifacts, area/projects, has-closing-pr
