### ISSUE TITLE
Implement Training also with SageMaker

### ISSUE THREAD

**Issue by whiletruelearn** [mlflow/mlflow#512] opened 2018-09-18 11:54 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: NA
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux
- **MLflow installed from (source or binary)**:  source
- **MLflow version (run ``mlflow --version``)**: 0.6
- **Python version**:  2.7
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
Currently , i see that training is not implemented with the SageMaker API. This will be a good feature to have. 

### Source code / logs
I can see [here](https://github.com/mlflow/mlflow/blob/master/mlflow/sagemaker/container/__init__.py#L140) comment that Training is not  implemented yet.

**Comment by mparkhe** [comment] 2019-07-26 21:45
Duplicate of #482

**Closed by mparkhe** 2019-07-26 21:45 UTC
