### ISSUE TITLE
RunId not found when executing "mlflow run" with remote tracking server

### ISSUE THREAD

**Issue by dmarkhas** [mlflow/mlflow#608] opened 2018-10-07 15:03 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**: 0.7.0
- **Python version**: 3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem

I have followed the tutorial and was able to get everything to work, and then added remote tracking to the train.py script so it will log everything to a remote mlflow server. That works well when executing the script directly via python, but when packaging that same script and using `mlflow run` to run it, I am observing errors that indicate mlflow is generating a unique experiment ID and then trying to look it up in the remote tracking server, and fails.

The client-side (where `mlflow run` runs) error is:

> icsl6700> .venv/bin/mlflow run tutorial -P alpha=0.42
> === Created directory /tmp/tmp65fqzyo2 for downloading remote URIs passed to arguments of type 'path' ===
> === Running command 'source activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac && python train.py 0.42 0.1' in run with ID '63e35b4f66164976b27f3d849c0fe72e' === 
> API request to http://mlflow-server:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 2 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
> API request to http://mlflow-server:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 1 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
> API request to http://mlflow-server:5000/api/2.0/preview/mlflow/runs/get failed with code 500 != 200, retrying up to 0 more times. API response body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
> Traceback (most recent call last):
>   File "train.py", line 40, in <module>
>     with mlflow.start_run():
>   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/tracking/fluent.py", line 105, in start_run
>     active_run_obj = MlflowClient().get_run(existing_run_uuid)
>   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/tracking/client.py", line 37, in get_run
>     return self.store.get_run(run_id)
>   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 132, in get_run
>     response_proto = self._call_endpoint(GetRun, req_body)
>   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/store/rest_store.py", line 68, in _call_endpoint
>     json=json_body)
>   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/utils/rest_utils.py", line 53, in http_request
>     (url, retries))
> mlflow.exceptions.MlflowException: API request to http://mlflow-server:5000/api/2.0/preview/mlflow/runs/get failed to return code 200 after 3 tries
> 

And the server-side error is:

> Oct 07 17:38:49 icsl6688 mlflow[19938]: [2018-10-07 17:38:49,690] ERROR in app: Exception on /api/2.0/preview/mlflow/runs/get [GET]
> Oct 07 17:38:49 icsl6688 mlflow[19938]: Traceback (most recent call last):
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     response = self.full_dispatch_request()
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     rv = self.handle_user_exception(e)
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     reraise(exc_type, exc_value, tb)
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     raise value
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     rv = self.dispatch_request()
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     return self.view_functions[rule.endpoint](**req.view_args)
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/server/handlers.py", line 218, in _get_run
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     response_message.run.MergeFrom(_get_store().get_run(request_message.run_uuid).to_proto())
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/store/file_store.py", line 296, in get_run
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     run_info = self._get_run_info(run_uuid)
> Oct 07 17:38:49 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/store/file_store.py", line 310, in _get_run_info
> Oct 07 17:38:49 icsl6688 mlflow[19938]:     raise Exception("Run '%s' not found" % run_uuid)
> Oct 07 17:38:49 icsl6688 mlflow[19938]: Exception: Run '6c72666f96ff4e0fbd7cb2002f074460' not found

Since mlflow run sets a random runid in the environment, mlflow picks it up and tries to look it up in the tracking server - and fails.
Perhaps I am missing something about the correct use-case of `mlflow run` but assuming packaged code can contain a remote tracking URI, won't it always cause it to fail when somebody else tries to run that packaged code with `mlflow run`?

**Comment by dmarkhas** [comment] 2018-10-07 15:10
Apparently this is also described in https://github.com/mlflow/mlflow/issues/572#issuecomment-426213131

**Comment by mparkhe** [comment] 2018-10-08 19:39
hi @dmarkhas : Can you also send me the list of env variables used. `MlflowClient` seems to be correctly instantiating `RestStore`. However, when looking up the run since you are not supplying any `--run_id` from command like for `mlflow run ....` command, I wonder if it picking up env variable `MLFLOW_RUN_ID`

**Comment by dmarkhas** [comment] 2018-10-08 20:03
Apparently `mlflow run` actually sets that environment variable by itself for some reason (which then follows the correct logic of trying to "resume" - but I don't think it should be setting it in the first place).

**Comment by mparkhe** [comment] 2018-10-08 20:24
You are right that `mlflow run` will create a subprocess with active run ID sent with environment setting. However, a couple of things are not adding up to me. Maybe you can help answer those.

Your client side code shows run ID as `63e35b4f66164976b27f3d849c0fe72e` from the log your posted.

```
=== Running command 'source activate mlflow-3eee9bd7a0713cf80a17bc0a4d659bc9c549efac && python train.py 0.42 0.1' in run with ID '63e35b4f66164976b27f3d849c0fe72e' ===
```

however the server side error is looking for another run ID `6c72666f96ff4e0fbd7cb2002f074460`. that should not happen. Do you know if this is the right stack. Also does either of the runs exist in your server running remotely. If you could `cd mlruns` folder and see in the appropriate experiment.

**Comment by dmarkhas** [comment] 2018-10-09 08:30
I apologize, it was a copy-paste error, this is the correct stack trace from the server (with the matching ID):


> Oct 07 17:35:38 icsl6688 mlflow[19938]: [2018-10-07 17:35:38,032] ERROR in app: Exception on /api/2.0/preview/mlflow/runs/get [GET]
> Oct 07 17:35:38 icsl6688 mlflow[19938]: Traceback (most recent call last):
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     response = self.full_dispatch_request()
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     rv = self.handle_user_exception(e)
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     reraise(exc_type, exc_value, tb)
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     raise value
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     rv = self.dispatch_request()
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     return self.view_functions[rule.endpoint](**req.view_args)
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/server/handlers.py", line 218, in _get_run
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     response_message.run.MergeFrom(_get_store().get_run(request_message.run_uuid).to_proto())
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/store/file_store.py", line 296, in get_run
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     run_info = self._get_run_info(run_uuid)
> Oct 07 17:35:38 icsl6688 mlflow[19938]:   File "/nfs/site/disks/ibi_tools/workarea/dmarkhas/python/.venv/lib/python3.6/site-packages/mlflow/store/file_store.py", line 310, in _get_run_info
> Oct 07 17:35:38 icsl6688 mlflow[19938]:     raise Exception("Run '%s' not found" % run_uuid)
> Oct 07 17:35:38 icsl6688 mlflow[19938]: Exception: Run '63e35b4f66164976b27f3d849c0fe72e' not found

The run does not exist on the server.

**Comment by anisnouri** [comment] 2018-10-31 14:38
Facing the same issue. Any progress or workaround?
thanks

**Comment by aakashganga** [comment] 2019-01-14 23:58
same issue here. Any progress?

**Comment by smurching** [comment] 2019-01-15 09:02
One thing that may be helpful (though I'm not sure if it's applicable in your cases) - calling `mlflow.set_tracking_uri("http://some-uri")` within your Python script and then attempting to execute the script via `mlflow run` won't work unless you set the `MLFLOW_TRACKING_URI` environment variable to the same value before invoking `mlflow run`, e.g. via `MLFLOW_TRACKING_URI=http://some-uri mlflow run ...`. 

This is because (as @sonnehansen mentioned) `mlflow run` first creates a run against the currently-configured tracking URI (so by default, the ./mlruns directory on your local filesystem) and then attempts to load that run when `start_run` is called in your Python script - if the tracking URIs are different in the two cases, you may see the abovementioned errors.

**Comment by gnthibault** [comment] 2019-07-04 11:02
Thank you @smurching  that solved the problem for me

**Comment by dbczumar** [comment] 2019-07-26 21:55
I'm going to close this issue since @smurching seems to have provided a solution. Please feel free to reopen it if this is still occurring.

**Closed by dbczumar** 2019-07-26 21:55 UTC

**Comment by Tyrannas** [comment] 2020-03-31 09:24
Ok I think https://github.com/mlflow/mlflow/issues/2649 is duplicate of this one. But is it really solved? I agry that @smurching solution is working but is this really the optimal behaviour? 

Seems to me that setting the uri in the script looks cleaner than setting mannualy an env variable.

**Comment by ividal** [comment] 2020-06-02 20:38
Stumbled upon this problem with v1.8.0.

Is the behaviour @smurching mentioned the intended one? The solution feels like a workaround. 

It is not always possible to set the env var on the terminal you will run a project in, so it would be handy to be able to use `mlflow.set_tracking_uri("http://some-uri")`. 

Thank you.

**Comment by techtutorco** [comment] 2020-06-15 21:25
I also have de same issue with version 1.8.0. I've tried both with MLFLOW_TRACKING_URI and mlflow.set_tracking_uri. 

When I use MLFLOW_TRACKING_URI, is not connecting to the server but just storing the runs in the project's mlruns project.

**Comment by EKami** [comment] 2021-02-04 10:04
This issue is still here as of mlflow `1.13.1`. The problem I have is that if I specify the tracking URI in `MLFLOW_TRACKING_URI` instead of `mlflow.set_tracking_uri` I am not able to dynamically load my dotenv environment. I have to make sure that in every single place `mlflow run` is run, the  `MLFLOW_TRACKING_URI` is defined beforehand. Or the alternative is just to not run with `mlflow run` but `python -m ...`.

**Comment by saigokarakonda1** [comment] 2021-04-02 22:05
I've set TRACKING_URI in the code as mlflow.set_tracking_uri(my uri) but how can i add env variable  MLFLOW_TRACKING_URI during mlflow run?

**Comment by BartlomiejSkwira** [comment] 2021-04-21 12:23
In my case it was just a matter of moving the `mlflow.set_tracking_uri` above `mlflow.start_run()`

So I changed **from this**:
```
    with mlflow.start_run() as run:
        mlflow.set_tracking_uri('http://localhost:5000')
        log_param("param1", randint(0, 100))
```
**To this:**
```
    mlflow.set_tracking_uri('http://localhost:5000')
    with mlflow.start_run() as run:
        log_param("param1", randint(0, 100))
```

**Comment by internetofjames** [comment] 2021-11-23 19:24
I'm running into this issue with mlflow `1.21.0`. Specifically, I'm trying to run an MLFlow project that is a slightly modified version of the wine example provided at [https://github.com/mlflow/mlflow/tree/master/examples/docker](https://github.com/mlflow/mlflow/tree/master/examples/docker) via docker on my Mac. I've got a tracking server running at `localhost:5000`.

```
mlflow.set_tracking_uri(os.getenv("MLFLOW_TRACKING_URI", "http://localhost:5000"))
mlflow.set_experiment("poc-with-sklearn-model")
```
are set _before_ `with mlflow.start_run()` is called. I read about allowing the docker container to access the host network, and so I've set `MLFLOW_TRACKING_URI=http://host.docker.internal:5000` in the `MLProject` file when running the script via `mlflow run`.

A sample output of `mlflow run . -P alpha=0.1`:

```
2021/11/23 12:56:40 INFO mlflow.projects.docker: === Building docker image mlflow-poc-train-docker ===
2021/11/23 12:56:40 INFO mlflow.projects.utils: === Created directory /var/folders/f3/nbbsbdtx57q7tzzcy1svxbvxrfndg5/T/tmpzpxbphej for downloading remote URIs passed to arguments of type 'path' ===
2021/11/23 12:56:40 INFO mlflow.projects.backend.local: === Running command 'docker run --rm -v /Users/me/repos/poc/ml-flow/ml-flow-training/mlruns:/mlflow/tmp/mlruns -v /Users/me/repos/poc/ml-flow/ml-flow-training/mlruns/0/6eb42950b07745b491691329daad9ad4/artifacts:/Users/me/repos/poc/ml-flow/ml-flow-training/mlruns/0/6eb42950b07745b491691329daad9ad4/artifacts -v $HOME/.aws:/home/.aws -e MLFLOW_RUN_ID=6eb42950b07745b491691329daad9ad4 -e MLFLOW_TRACKING_URI=http://host.docker.internal:5000 -e MLFLOW_EXPERIMENT_ID=1 -e HOME=/home mlflow-poc-train-docker:latest python src/train.py --alpha 0.1 --l1-ratio 0.1' in run with ID '6eb42950b07745b491691329daad9ad4' === 
Traceback (most recent call last):
  File "src/train.py", line 68, in <module>
    with mlflow.start_run():
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/fluent.py", line 204, in start_run
    active_run_obj = client.get_run(existing_run_id)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/client.py", line 150, in get_run
    return self._tracking_client.get_run(run_id)
  File "/usr/local/lib/python3.7/site-packages/mlflow/tracking/_tracking_service/client.py", line 65, in get_run
    return self.store.get_run(run_id)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 135, in get_run
    response_proto = self._call_endpoint(GetRun, req_body)
  File "/usr/local/lib/python3.7/site-packages/mlflow/store/tracking/rest_store.py", line 56, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 217, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/usr/local/lib/python3.7/site-packages/mlflow/utils/rest_utils.py", line 169, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: RESOURCE_DOES_NOT_EXIST: Run with id=6eb42950b07745b491691329daad9ad4 not found
2021/11/23 12:56:43 ERROR mlflow.cli: === Run (ID '6eb42950b07745b491691329daad9ad4') failed ===
```

If it helps further clarify, my tracking server that is running locally uses a locally running postges docker container as a backend store and an S3 bucket as an artifact root.

The python script works when I run it directly, but not as an MLProject with a docker environment. I'm new to `mlflow`, but based on the output, it seems like it's still trying to create the tracking server locally as i get an `mlruns` directory in my local repo after trying to run the project.

**Comment by pcjedi** [comment] 2021-12-22 15:57
for me this helped:

```python
experiment_name = "my_experiment"

mlflow.set_experiment(experiment_name)
experiment = mlflow.get_experiment_by_name(experiment_name)
client = mlflow.tracking.MlflowClient()
run = client.create_run(experiment.experiment_id)
with mlflow.start_run(run_id = run.info.run_id):
    pass # do stuff now
```

**Comment by zimonitrome** [comment] 2023-05-25 15:29
I still have issues with this setting MLFLOW_TRACKING_URI to "databricks".

Then running:

```
mlflow.projects.run(
    uri=".",
    entry_point=...,
    parameters={
        ...
    },
    experiment_id=...,
    env_manager="conda",
    backend="databricks",
    backend_config=...,
    synchronous=False,
)
```

Can the above fixes be adapted for `mlflow.projects.run`.

**Comment by mshajarrazip** [comment] 2023-07-20 13:59
On version 2.5.0, this is still an issue for me. Works fine if I run the python script directly but not working when using `mlflow run`. Tried both @smurching and @BartlomiejSkwira's suggestions but no luck.

**Comment by Mukilan-Mohanachandran** [comment] 2024-07-12 11:20
@Tyrannas instead of setting env in terminal you can use os.environ['MLFLOW_TRACKING_URI'] = 'http://yourhost:5000' to automate the script, this will solve the problem ig
