### ISSUE TITLE
[FR] Highlight different parameters when comparing experiments

### ISSUE THREAD

**Issue by xgk** [mlflow/mlflow#2134] opened 2019-11-24 11:56 UTC
Thank you for submitting an issue. Please refer to our [issue policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)
for information on what types of issues we address.

Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

-------
## Guidelines

Feature requests typically go through the following lifecycle:

1. Submit feature request with high-level description on GitHub issues (this is what you're doing now)
2. Discuss feature request with a committer, who may ask for a more detailed design
3. After discussion & agreement on feature request, start implementation

## Describe the proposal
Highlight differences of parameters when comparing 

### Motivation
Make the comparing easier to find differences

### Proposed Changes
Highlight differences of parameters when comparing

**Comment by AzharSultan** [comment] 2020-02-11 14:22
Any traction on this? Right now it is impossible to see difference in parameters if there are too many parameters in the experiment. I am not a javascript guy, , but I expect the changes will need to happen at [CompareRunView.js](https://github.com/mlflow/mlflow/blob/master/mlflow/server/js/src/components/CompareRunView.js#L150) where the list is filtered for params not matching across compared runs.

**Comment by clara2911** [comment] 2020-05-20 15:08
Duplicate of this feature request here: https://github.com/mlflow/mlflow/issues/1653
Seems to be solved and closed

**Comment by dbczumar** [comment] 2020-07-01 22:51
Thanks folks, closing this as a duplicate of #2565

**Closed by dbczumar** 2020-07-01 22:51 UTC
Labels: enhancement
