### ISSUE TITLE
bug: mlflow in R fail to call mlflow_param

### ISSUE THREAD

**Issue by harryprince** [mlflow/mlflow#854] opened 2019-01-29 07:52 UTC
### System information

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS: /data/opt/R/3.4.2/lib64/R/lib/libRblas.so
LAPACK: /data/opt/R/3.4.2/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mapdeck_0.2.1       sparklyr_0.9.3.9000 mapview_2.3.0      
 [4] bindrcpp_0.2.2      flexdashboard_0.5.1 forcats_0.2.0      
 [7] stringr_1.3.1       dplyr_0.7.8         readr_1.1.1        
[10] tidyr_0.8.2         tibble_2.0.1        ggplot2_3.1.0      
[13] tidyverse_1.2.1    

loaded via a namespace (and not attached):
  [1] colorspace_1.3-2       class_7.3-14           gdalUtils_2.0.1.7     
  [4] leaflet_2.0.2          rgdal_1.3-6            rprojroot_1.3-2       
  [7] satellite_1.0.1        fs_1.2.6               base64enc_0.1-3       
 [10] rstudioapi_0.9.0       fansi_0.4.0            lubridate_1.7.4       
 [13] xml2_1.2.0             codetools_0.2-15       R.methodsS3_1.7.1     
 [16] knitr_1.21             config_0.3             jsonlite_1.6          
 [19] broom_0.5.0            dbplyr_1.2.2           leafletCN_0.2.1       
 [22] png_0.1-7              R.oo_1.21.0            jsonify_0.2.0         
 [25] shiny_1.2.0            compiler_3.4.2         httr_1.4.0            
 [28] backports_1.1.2        Matrix_1.2-14          assertthat_0.2.0      
 [31] lazyeval_0.2.1         cli_1.0.1              later_0.7.5           
 [34] htmltools_0.3.6        tools_3.4.2            gtable_0.2.0          
 [37] glue_1.3.0             rappdirs_0.3.1         Rcpp_1.0.0.1          
 [40] cellranger_1.1.0       raster_2.8-4           debugme_1.1.0         
 [43] nlme_3.1-131           iterators_1.0.9        crosstalk_1.0.0       
 [46] xfun_0.4               rvest_0.3.2            mime_0.6              
 [49] devtools_1.13.4        scales_1.0.0           hms_0.4.0             
 [52] promises_1.0.1         parallel_3.4.2         swagger_3.9.2         
 [55] yaml_2.2.0             curl_3.2               memoise_1.1.0         
 [58] reticulate_1.10.0.9003 forge_0.1.0            stringi_1.2.4         
 [61] foreach_1.4.4          e1071_1.7-0            leaflet.extras_1.0.0  
 [64] rlang_0.3.1            pkgconfig_2.0.2        evaluate_0.12         
 [67] lattice_0.20-35        bindr_0.1.1            sf_0.7-2              
 [70] htmlwidgets_1.3        tidyselect_0.2.5       processx_3.2.1        
 [73] plyr_1.8.4             magrittr_1.5           R6_2.3.0              
 [76] DBI_1.0.0              carrier_0.1.0          pillar_1.3.1          
 [79] haven_1.1.2            withr_2.1.2.9000       units_0.6-2           
 [82] sp_1.3-1               modelr_0.1.1           crayon_1.3.4          
 [85] utf8_1.1.4             rmarkdown_1.11         grid_3.4.2            
 [88] readxl_1.0.0           git2r_0.24.0           colourvalues_0.2.2    
 [91] digest_0.6.18          classInt_0.3-1         webshot_0.5.0         
 [94] xtable_1.8-3           httpuv_1.4.5.1         r2d3_0.2.2            
 [97] R.utils_2.7.0          openssl_1.2.1          stats4_3.4.2          
[100] munsell_0.5.0          viridisLite_0.3.0  
```

### Describe the problem

mlflow::mlflow_param does not work due to `forge::cast_choice` bug.

I check the `mlflow::mlflow_param` source code:

```
function (name, default = NULL, type = NULL, description = NULL) 
{
    target_type <- forge::cast_choice(type, c("numeric", "integer", 
        "string"), allow_null = TRUE) %||% typeof(default)
    if (identical(target_type, "NULL")) 
        stop("At least one of `default` or `type` must be specified", 
            call. = FALSE)
    caster <- switch(target_type, integer = forge::cast_nullable_scalar_integer, 
        double = forge::cast_nullable_scalar_double, numeric = forge::cast_nullable_scalar_double, 
        forge::cast_nullable_string)
    default <- tryCatch(if (!is.null(default)) 
        caster(default), error = function(e) stop("`default` value for `", 
        name, "` cannot be casted to type ", type, ": ", conditionMessage(e), 
        call. = FALSE))
    tryCatch(caster(.globals$run_params[[name]]) %||% default, 
        error = function(e) stop("Provided value for `", name, 
            "` cannot be casted to type ", type, ": ", conditionMessage(e), 
            call. = FALSE))
}
<bytecode: 0x5582282f2c38>
<environment: namespace:mlflow>
```

And I found `forge::cast_choice` source code:
```
function (.x, .choices, .allow_na = FALSE, .allow_null = FALSE, 
    .id = NULL) 
{
    .id <- resolve_id(rlang::enquo(.x), .id)
    cast <- switch(rlang::type_of(.choices), integer = cast_scalar_integer, 
        double = cast_scalar_double, string = cast_scalar_character, 
        character = cast_scalar_character)
    if (is.null(cast)) 
        stop("`.choices` must be a vector of numbers or strings.", 
            call. = FALSE)
    if (rlang::is_na(.x)) {
        if (.allow_na) 
            return(new_forge_stamped(.x, .id = .id))
        else stop(backticks(.id), " must not be NA.", call. = FALSE)
    }
    if (rlang::is_null(.x)) {
        if (.allow_null) 
            return(NULL)
        else stop(backticks(.id), " must not be NULL.", call. = FALSE)
    }
    casted <- cast(.x)
    if (casted %in% .choices) 
        new_forge_stamped(casted, .id = .id)
    else stop(backticks(.id), " must be one of ", paste0(.choices, 
        collapse = ", "), ".", call. = FALSE)
}
<bytecode: 0x558224bcec78>
<environment: namespace:forge>
```

the argument `allow_null` and `.allow_null` are inconsistent.

### Source code / logs

R/mlflow seems bugy:

```
library(mlflow)
mlflow_set_tracking_uri("http://0.0.0.0:5000")
mlflow_set_experiment("pp_v2")
my_int <- mlflow_param("my_int", 1, "integer")
```

```
Error in forge::cast_choice(type, c("numeric", "integer", "string"), allow_null = TRUE): unused argument (allow_null = TRUE)
```
I think @kevinykuo should notice this issue.

**Comment by dkincaid** [comment] 2019-01-31 22:32
Finally getting a chance to look into mlflow and hit this bug 10 minutes in at the very beginning of the tutorial.

**Comment by kevinykuo** [comment] 2019-01-31 22:37
Could you guys use forge from CRAN or the latest devel? If you're still running into the issue please provide output of `devtools::session_info()`.

**Comment by dkincaid** [comment] 2019-01-31 22:39
I can do it to give it a try, but that will likely break other packages. Specifically sparklyr which seems ultra sensitive to the forge version also.

**Comment by dkincaid** [comment] 2019-01-31 22:44
I can confirm that it does work with forge from CRAN (version 0.1.0). The version I had that it wasn't working with was version 0.1.9002 which I think was installed by sparklyr.

**Comment by kevinykuo** [comment] 2019-01-31 22:45
@dkincaid yeah we removed the requirement for devel forge in devel sparklyr a few days ago so I think you should be okay.

**Comment by dkincaid** [comment] 2019-01-31 22:49
That is great news @kevinykuo. Thanks.

**Comment by kevinykuo** [comment] 2019-02-07 00:18
Closing, also I've updated forge to be compatible so users shouldn't run into this in the future.

**Closed by kevinykuo** 2019-02-07 00:18 UTC

**Comment by knjenga** [comment] 2019-08-01 19:10
I am still getting the problem "Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  Command not found" after installing everything from scratch and trying to run the examples at https://mlflow.org/docs/latest/tutorial.html.

This is a bummer because it holds great promise for what we can do with mlfow.

R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlflow_1.1.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1      magrittr_1.5    lattice_0.20-38 R6_2.4.0        rlang_0.3.2     httr_1.4.0      tools_3.5.3     grid_3.5.3      withr_2.1.2    
[10] askpass_1.1     openssl_1.3     yaml_2.1.19     forge_0.2.0     processx_3.3.0  Matrix_1.2-15   ini_0.3.1       purrr_0.2.5     later_0.8.0    
[19] fs_1.2.7        base64enc_0.1-3 promises_1.0.1  ps_1.3.0        zeallot_0.1.0   compiler_3.5.3  swagger_3.9.2   reticulate_1.13 jsonlite_1.5   
[28] httpuv_1.5.0
