### ISSUE TITLE
sklearn autolog and TfidfVectorizer do not work together

### ISSUE THREAD

**Issue by sheldonkhall** [mlflow/mlflow#3574] opened 2020-10-22 09:24 UTC
When running this minimal example with mlflow autolog:

```
from sklearn.feature_extraction.text import TfidfVectorizer
import mlflow

mlflow.sklearn.autolog()

X_train = ['blah blah blah blah', 'ho ho ho ho']
tfidf_count = TfidfVectorizer()
tfidf_count.fit(X_train)
tfidf_count.transform(X_train).toarray()
```

I get a strange error that I cannot understand about `RecursionError: maximum recursion depth exceeded`. However if I remove the autolog statement and run this:

```
from sklearn.feature_extraction.text import TfidfVectorizer
import mlflow

# mlflow.sklearn.autolog()

X_train = ['blah blah blah blah', 'ho ho ho ho']
tfidf_count = TfidfVectorizer()
tfidf_count.fit(X_train)
tfidf_count.transform(X_train).toarray()
```

everything works just fine.

I am on scikit-learn==0.23.2, mlflow==1.11.0.

**Comment by harupy** [comment] 2020-10-22 15:13
@sheldonkhall Thanks for reporting this. I was able to reproduce the issue.

**Comment by dmatrix** [comment] 2020-10-22 16:35
@harupy Thanks for jumping on it!

**Comment by harupy** [comment] 2020-10-23 01:01
Wrote a simple script to repro & investigate the issue:

```python
import functools
import gorilla


def wrap_patch(destination, name, patch, settings=None):
    if settings is None:
        settings = gorilla.Settings(allow_hit=True, store_hit=True)

    original = getattr(destination, name)
    wrapped = functools.wraps(original)(patch)
    patch = gorilla.Patch(destination, name, wrapped, settings=settings)
    gorilla.apply(patch)


class CountVectorizer:
    def fit_transform(self):
        print("CountVectorizer.fit_transform called")


class TfidfVectorizer(CountVectorizer):
    def fit_transform(self):
        print("TfidfVectorizer.fit_transform called")
        super().fit_transform()


FUNC_NAME = "fit_transform"


def fit_transform1(self, *args, **kwargs):
    original_fit1 = gorilla.get_original_attribute(self, FUNC_NAME)
    print("fit_transform1 called")
    return original_fit1(*args, **kwargs)


def fit_transform2(self, *args, **kwargs):
    original_fit2 = gorilla.get_original_attribute(self, FUNC_NAME)
    print("fit_transform2 called")
    return original_fit2(*args, **kwargs)


wrap_patch(TfidfVectorizer, FUNC_NAME, fit_transform1)
wrap_patch(CountVectorizer, FUNC_NAME, fit_transform2)


tfidf = TfidfVectorizer()
tfidf.fit_transform()

# output:
"""
fit_transform1 called
TfidfVectorizer.fit_transform called
fit_transform2 called
TfidfVectorizer.fit_transform called
...

RecursionError: maximum recursion depth exceeded while calling a Python object
"""


# How this error occurs:
"""
1. `TfidfVectorizer.fit_transform` called
2. `fit_transform1` called
3. `original_fit1` (the original `TfidfVectorizer.fit_transform`) called
4. `super().fit_transform` (= `CountVectorizer.fit_transform`) called
5. `fit_transform2` is called
6. `original_fit2` (the original `TfidfVectorizer.fit_transform`) called
7. Goes back to step 4 (== infinite loop)
"""

```

**Comment by dbczumar** [comment] 2020-10-23 06:48
Hi folks, I dug into this and found the root cause + a potential fix. There were two issues - one in gorilla itself and one with our usage of gorilla: 

1. In gorilla 0.3.0, applying a patch that stores a hit to a parent class (e.g., `CountVectorizer`) forces `get_original_attribute` of its children to refer to the parent class attribute, even if we patch the child later on. I.e.

This ordering is okay
```
gorilla.Patch(<TfidfVectorizer>)
gorilla.Patch(<CountVectorizer>)
```

but this ordering is not

```
gorilla.Patch(<CountVectorizer>)
gorilla.Patch(<TfidfVectorizer>)
```

This appears to be caused by the following line that prevents the original attribute from being overwritten once it's set: https://github.com/christophercrouzet/gorilla/blob/0c895b34311b6546bde35854e24862c001279add/gorilla.py#L280. As a result, setting the attribute on the parent, which sets the original attribute on the child if the child does not already define it, means that the child is always stuck with the parent's original attribute. This seems to be fixed in the `master` branch of gorilla but has not been released. Either we can pull in the copy from `master` or pull in a copy from 0.3.0 that removes this problematic `hasattr` check.

2. In `fit_mlflow` and `fit_predict`, we perform `get_original_attribute(self, func_name)`. In the case where we're in a super class function (e.g., `CountVectorizer.fit_transform()`), `self` still refers to the subclass (e.g., `TfidfVectorizer`). As a result, calling `get_original_attribute` in the patched super class method fetches and invokes the patched subclass method, which creates the infinite recursion problem observed in the issue description. I've filed https://github.com/mlflow/mlflow/pull/3582/ to address this problem by fetching the original function attribute by reference to a class rather than by reference to `self`. This PR still needs docs & tests, and it needs to incorporate a fix for (1) before its mergeable.

@harupy Let me know what your thoughts are here.

**Closed** 2020-10-27 06:26 UTC
Labels: area/tracking, bug, priority/important-soon
