### ISSUE TITLE
Error initializing backend store when MySQL is used in 1.1.0

### ISSUE THREAD

**Issue by smudiyam** [mlflow/mlflow#1704] opened 2019-08-07 11:24 UTC
We are using MySQL Ver 8.0.17 as backend in mlflow 1.1.0. When we are trying to start the server with MySQL as backend, we are getting the following error

2019/08/02 09:43:43 ERROR mlflow.cli: Error initializing backend store  
2019/08/02 09:43:43 ERROR mlflow.cli: Detected out-of-date database schema (found version None, but expected 181f10493468). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail. 

At this point, it just created two tables "alembic_version" and "experiments" in the database. As per error messages, we tried 'mlflow db upgrade'. Then, we are getting the following error

sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) (1146, "Table 'mlflow.runs' doesn't exist")  
[SQL: ALTER TABLE runs ADD CONSTRAINT runs_lifecycle_stage CHECK (lifecycle_stage IN ('active', 'deleted'))]  
(Background on this error at: http://sqlalche.me/e/f405)   

Here, upgrade is trying to add constraint to table "runs" which is not even created when we started the server. So, we have created "runs" table manually and then ran "upgrade" command again. Then, it throws similar error for "metrics", "tags" and other required tables.

As a workaround, we have created all missing tables manually and ran "upgrade" command successfully and started the server.

**Comment by ankitmathur-db** [comment] 2019-08-07 20:22
To clarify, is the workflow here that you started with a fresh database, ran mlflow server, and then experienced an error initializing the DB? If so, that error should have popped up before you ran mlflow db upgrade.

**Comment by smudiyam** [comment] 2019-08-13 13:50
Yes, we started with a fresh database and ran mlflow server and then it thrown error initializing backend store and asked to run "mlflow db upgrade". At this point, (after mlflow server and before mlflow db upgrade), only two tables (alembic_version and experiments) were created in the database.

And then, we ran "mlflow db upgrade" but it thrown this error "Table 'mlflow.runs' doesn't exist". Problem here is that "mlflow server" is not creating all the tables required even with a fresh database and "mlflow db upgrade" doesn't create them if they are not present.

So, we run mlflow server and create missing tables manually and then run mlflow db upgrade.

**Comment by abhishekmm** [comment] 2020-01-10 08:16
mlflow server --backend-store-uri mysql://user:'password'@localhost:3306/mlrun --default-artifact-root C:\mlflowrepo\mlflow-artifacts --host 0.0.0.0
2020/01/10 13:15:13 ERROR mlflow.cli: Error initializing backend store
2020/01/10 13:15:13 ERROR mlflow.cli: (MySQLdb._exceptions.OperationalError) (1045, "Access denied for user 'mluser'@'localhost' (using password: YES)")
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by dbczumar** [comment] 2020-03-06 22:53
@smudiyam Tables for an MLflow Tracking database should be created as soon the server is started; I'm unfortunately unable to reproduce the partial table creation scenario. Did an error occur during table creation prior to your invocation of `mlflow db upgrade`? 

It sounds like manual table creation was successful and that you are unblocked. For the time being, I am going to close this issue. If you're still facing partial table creation problems, please feel free to reopen this.

**Closed by dbczumar** 2020-03-06 22:53 UTC
Labels: will-fix
