### ISSUE TITLE
[FR] Log local variables

### ISSUE THREAD

**Issue by mgbckr** [mlflow/mlflow#1724] opened 2019-08-11 20:22 UTC
# Logging local variables
## Describe the proposal
Currently logging parameters is a little cumbersome since you have to log each parameter separately. For this I suggest an addition to the fluent API that allows to just log all local variables with various parameters (e.g., only logging parameters of the current function, only logging local variables, etc.). This is currently only proposed for the Python API.

This functionality could be provided by an MLflow wrapper as exemplified here: [mlflowhelper](https://github.com/mgbckr/mlflowhelper)

### Proposed Changes

```python
import mlflow

def main(param1, param2, param3="defaultvalue", verbose=0, *args, **kwargs):
    some_variable = "x"
    with mlflow.start_run():
        mlflow.log_vars(exclude=["verbose"]) # logs local variables as parameters

if __name__ == '__main__':
    main("a", "b", something_else=6)
```
This will log:
```json
{
  "param1": "a",
  "param2": "b",
  "param3": "defaultvalue",
  "something_else": 6
}
```

A more complete version of the function can be found here: https://github.com/mgbckr/mlflowhelper/blob/master/src/mlflowhelper/tracking/fluent.py

**Comment by apurva-koti** [comment] 2019-08-12 19:53
Hi! Thanks for filing an issue. There is already an endpoint for logging metrics, parameters and tags in batch: https://www.mlflow.org/docs/latest/python_api/mlflow.tracking.html#mlflow.tracking.MlflowClient.log_batch

This is not exactly the same as automatically logging all local variables, but that does seem to me like a very specific use case that might not warrant its own endpoint. Does the above link address the need?

**Comment by mgbckr** [comment] 2019-08-13 03:53
Thanks for the link. However, I don't think `log_batch` provides comparable functionality. While it allows to log several things at the same time, it does not solve the issue "forgetting to log parameters". Automatically logging new local variables is important to implicitly catch new parameters as you develop your model script and ensures the complete coverage of your experimental environment.

**Comment by apurva-koti** [comment] 2019-08-13 04:58
I think there's a misunderstanding here. "Parameter" in the context of MLflow does not literally refer to Python function parameters, but rather any key-value (string-string) pair. See the [docs](https://www.mlflow.org/docs/latest/tracking.html#concepts) for more info on this. Typically, parameters describe your network in some way: learning rate, epsilon value, layer count, and so on. You can also view examples in the [examples folder.](https://github.com/mlflow/mlflow/tree/master/examples) 
  
Essentially, MLflow parameters have nothing to do with Python function parameters. In that sense "forgetting to log parameters" isn't really MLflow's responsibility.

**Comment by mgbckr** [comment] 2019-08-13 05:38
Thanks for the quick answer. I am aware of the parameter concept, sorry for being a little vague here. Let's actually take an example from the examples repo (https://github.com/mlflow/mlflow/blob/master/examples/multistep_workflow/als.py). There are various parameters passed via @click.option to the train function that parameterize each run (and are actually quite essential to the run). These parameters are not logged in the example. To do this you would have to log them by hand:

```
mlflow.log_params({
"split_prop": split_prop,
"max_iter": max_iter,
# ...
})
```
With the proposed function, you simply write:
```
mlflow.log_vars()
```
And now if you would add, let's say `ALS` parameter to your command line, it would be automatically logged. 

Yes, logging those parameters is doable without the proposed function, but the proposed function will ease the development process tremendously and prevent missing parameters when logging runs. 

Maybe I am a little biased by `sacred` which basically logs everything for you automatically ;) Two different paradigms, I guess. 

I hope this makes a little more sense now.

**Comment by ankitmathur-db** [comment] 2019-08-13 17:02
One alternative that I typically use is I use `argparse` to take in command line arguments and use `log_batch` to log that. It precludes you from adding new parameters to your function, but if your function just takes args and main sets args, it can be pretty valuable. 

Regardless, it seems like your work on mlflowhelper includes code to do this! If you go ahead and file a PR against MLflow, we can review it and discuss if/how we can integrate this into the library.

**Comment by mgbckr** [comment] 2019-08-19 22:01
Cool, thanks for mentioning that alternative. 

And yes, since the code is there, I will go ahead and create a PR. Might not be tomorrow but it's on my list ;)

**Comment by mgbckr** [comment] 2019-09-12 04:01
As promised here is the PR: https://github.com/mlflow/mlflow/pull/1836

**Comment by smurching** [comment] 2019-09-13 08:32
@mgbckr thanks for the PR! I wonder if the use case in your example could be satisfied by running your Python script as an MLflow project. In particular, MLflow actually supports running Python scripts as projects & passing parameters to them on the command line, logging said parameters. You can run your provided script via `mlflow run /parent/directory/of/script -e script.py --no-conda -P firstparam=3 -P secondparam=4` - perhaps we could look into enhancing this functionality (or the docs, since it doesn't seem to be mentioned [here](https://mlflow.org/docs/latest/projects.html#running-projects) if it currently falls short?

**Comment by mgbckr** [comment] 2019-09-17 23:25
@smurching Thanks! I have to admit that I have not looked at the MLflow projectr module yet. I will look into it.

**Comment by mgbckr** [comment] 2019-09-18 01:34
OK, just looked into this. So it seems the project module kind of alleviates the need to log parameters in the first place. Meaning, that for logging parameters, `mlflow` would prefer the usage of the project functionality. Assuming that this is true, I think there is a little bit of an inconsistency:

Case 1: Parameter logging should be handled by the project module only. In this case, `mlflow.log_param` and `mlflow.log_params` should not exist, since all parameters should be handled through project functionality, i.e., calling an entry point. Looking at the multi-stage example project ([example](https://github.com/mlflow/mlflow/blob/977186ce49304e5a19b4fb101af5f518ed0c2a43/examples/multistep_workflow/als.py)), this seems to be the case since no parameters are explicitly logged. This would mean that the tracking module is not an independent project. 

Case 2: The tracking module is independent, thus supporting the use of a custom project structure without having to use the Mlflow project functionality. The whole `fluent` API (`start_run`, `log_param`) etc. points towards this use case.   

So, considering the `fluent` API, I think, Case 2 is the more likely. In this case my proposed `log_vars` function makes sense (i.e., for Case 2) in order to support convenient logging independent of the project module. 

Let me know what you think :)

As a side-note: I think having a side-by-side comparison of a tracking / `fluent`-based script and a project based setup  (discussing pros and cons) would be a really valuable asset for the documentation.

**Comment by LarsHill** [comment] 2019-11-16 13:36
I like the idea of logging all the parameters (in my case and probably also in most other cases coming from a config) automatically. As previously said, Sacred does the same by traversing nested configs and logging all parameters (key, value pairs).

Within the UI being able to disable unnecessary columns would be awesome.

**Comment by mgbckr** [comment] 2019-11-19 22:13
As I side note, I want to mention that the function as it is implemented right now only logs the parameters of the encasing function in order to avoid logging a crazy bunch of variables, e.g., in case of calling it in a Jupyter Notebook or something like that.

**Comment by mparkhe** [comment] 2020-04-07 04:43
I am going to close this issue since logging local  and environment variables can be unexpected behavior and leak some secret inadvertently, as discussed in [PR #1836](https://github.com/mlflow/mlflow/pull/1836#issuecomment-608895392)

**Closed by mparkhe** 2020-04-07 04:43 UTC
Labels: enhancement
