### ISSUE TITLE
[BUG] Mlflow transformers not supported for fill-mask task

### ISSUE THREAD

**Issue by s-aditi** [mlflow/mlflow#9143] opened 2023-07-24 07:25 UTC
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version
- 2.4.1

### System information

- **Python version**: 3.10

### Describe the problem

Face the following issue, when try to run predict on a mlflow fill-mask model.
Currently using the latest mlflow version ```2.4.1```
``` list indices must be integers or slices, not str ```

 ``` 
File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 428, in predict
    return self._predict_fn(data)
  File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/transformers.py", line 1636, in predict
    predictions = self._predict(input_data, device)
  File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/transformers.py", line 1757, in _predict
    output = self._parse_list_of_multiple_dicts(raw_output, output_key)
  File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/transformers.py", line 2150, in _parse_list_of_multiple_dicts
    return [collection[0][target_dict_key] for collection in output_data]
  File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/transformers.py", line 2150, in <listcomp>
    return [collection[0][target_dict_key] for collection in output_data]
TypeError: list indices must be integers or slices, not str 
```

### Stack trace

```
 File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/pyfunc/__init__.py", line 428, in predict
    return self._predict_fn(data)
  File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/transformers.py", line 1636, in predict
    predictions = self._predict(input_data, device)
  File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/transformers.py", line 1757, in _predict
    output = self._parse_list_of_multiple_dicts(raw_output, output_key)
  File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/transformers.py", line 2150, in _parse_list_of_multiple_dicts
    return [collection[0][target_dict_key] for collection in output_data]
  File "/azureml-envs/model-evaluation/lib/python3.8/site-packages/mlflow/transformers.py", line 2150, in <listcomp>
    return [collection[0][target_dict_key] for collection in output_data]
TypeError: list indices must be integers or slices, not str

```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [X] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment] 2023-07-24 08:06
@s-aditi Can you provide code to reproduce the issue?

**Comment by s-aditi** [comment] 2023-08-01 05:52
@harupy This is the notebook i used - https://github.com/Azure/azureml-examples/blob/main/sdk/python/foundation-models/system/evaluation/fill-mask/fill-mask.ipynb

However rather than using the fill-mask model from azureml-registry I used a huggingface model converted using mlflow.transformer, using the following code
``` 
from transformers import AutoTokenizer, AutoModelForMaskedLM

model name = "bert-base-cased"

def fillmask_funct(model_name):

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForMaskedLM.from_pretrained(model_name)
    # model = AutoModel.from_pretrained("distilbert-base-cased")


    components = {
        "model": model,
        "tokenizer": tokenizer,
    }
    mlflow.transformers.save_model(
        transformers_model=components,
        path=model_name,
    )

    mdl = mlflow.pyfunc.load_model(model_name)
  
```

**Comment by BenWilson2** [comment] 2023-08-01 15:57
Hi @s-aditi thank you for reporting this. We'll try to get a fix for this for the next release of MLflow!

**Comment by ShipraJain01** [comment] 2023-08-02 04:22
hi @BenWilson2,
Could you share a tentative ETA on the fix?

Regards,
Shipra

**Comment by BenWilson2** [comment] 2023-08-02 15:14
I'm going to be working on the fix in the next few days, pending some other work that I'm finishing up.

**Comment by BenWilson2** [comment] 2023-08-07 23:25
Hi @s-aditi I just got around to working on a repro for this. 
In the code that you posted, there are a number of issues. 

Below are the modifications to use the exact model architecture that you defined. I've confirmed that the model works as intended. 

Please run the following to confirm:

```python
from transformers import AutoTokenizer, AutoModelForMaskedLM
import mlflow

# define the model architecture that will be fetched from huggingface_hub
model_architecture = "bert-base-cased"

# define an artifact path to use for saving the pipeline artifact components
model_name = "mask_model_2"

# Download and locally cache the appropriate tokenizer and model
tokenizer = AutoTokenizer.from_pretrained(model_architecture)
model = AutoModelForMaskedLM.from_pretrained(model_architecture)

# Define the components for the Masked Language Model
components = {
    "model": model,
    "tokenizer": tokenizer,
}

# Initialize the MLflow run context
with mlflow.start_run():
    # Log the transformers components to the defined artifact path
    mlflow.transformers.log_model(
        transformers_model=components,
        artifact_path=model_name,
    )
    # retrieve the absolute model_uri path
    model_uri = mlflow.get_artifact_uri(model_name)

# Load as pyfunc directly    
mdl = mlflow.pyfunc.load_model(model_uri)

# cli command for starting an MLflow serving instance for this model (run the output printed to stdout 
#  in your command line environment to spin up a local server to send REST requests to)
print(f"mlflow models serve -m {model_uri} -h 127.0.0.1 -p 9070 --no-conda")
```

To use the loaded pyfunc model directly:

```python 
mdl.predict("What [MASK] is this?")
mdl.predict(["I [MASK] using LLMs!", "I like to [MASK] apples and bananas"])
```

To validate the serving behavior, execute the printed statement from the first code block above in a new terminal window. Then, issue a REST POST to the endpoint:

```python
import requests
import json

url = "http://127.0.0.1:9070/invocations"

headers = {
    'Content-Type': 'application/json',
}

data = {
    "inputs": ["I like to [MASK] on an airplane", "[MASK] is the best color"],
}

response = requests.post(url, headers=headers, data=json.dumps(data))

print(response.content)
```

Can you verify that this works on your system?  
Feel free to open this ticket back up if you encounter additional issues, but I'm closing this due to the flavor demonstrating correct behavior with appropriate applied usage of it.

**Closed by BenWilson2** 2023-08-07 23:25 UTC
Labels: bug, area/models

**Comment by s-aditi** [comment] 2023-08-09 06:00
Hi @BenWilson2, I still face the same issue. 
`mdl.predict` was working for me earlier as well. However, when I use this model in the above shared notebook, I face this issue.
