### ISSUE TITLE
Log Artifact saves locally only

### ISSUE THREAD

**Issue by maoding** [mlflow/mlflow#902] opened 2019-02-19 06:41 UTC
### System information
- **Server**: Python 3.6.4 :: Anaconda, Inc.
- **Client**: Python 3.6.5
- **MLflow installed from (source or binary)**: pip
- **MLflow version**: both, server and client, 0.8.2
- **Exact command to reproduce**:
    - Server: ``mlflow server -h 0.0.0.0 --file-store /opt/mlruns/ --default-artifact-root /opt/mlruns/ -p 5050``
    - Client: 
        ```
        import mlflow
        mlflow.set_tracking_uri('http://xxx.mlflow.net:5050/')
        mlflow.create_experiment('test artifact')
        mlflow.set_experiment('test artifact')
        with mlflow.start_run(nested=True):
            mlflow.log_artifact('/data-dir/model.png', 'models')
        ```
### Describe the problem
I am running a mlflow server on a remote host. There are no special things configured for mlflow. Logging of parameters/metrics works like a charm. If I try to upload an artifact I get problems. The command executes without errors if I create the `/opt/mlruns` dir with proper permissions on my localhost. But only locally my data is saved NOT on the remote host where the server is running. There is no S3 or anything else involved, simple NFS mount. Any idea what I am doing wrong or where this goes wrong???

**Comment by dstine** [comment] 2019-02-19 18:45
I experienced this also. Artifacts are logged to a local directory on my client, instead of on the server as expected.

The logic in [artifact_repo.py](https://github.com/mlflow/mlflow/blob/v0.8.2/mlflow/store/artifact_repo.py#L95) doesn't have any case for HTTP, and this is the function used by [client.py](https://github.com/mlflow/mlflow/blob/v0.8.2/mlflow/tracking/client.py#L162). It appears the expectation is that if you run client and server on separate hosts, you should use one of the protocols that are covered.

**Comment by maoding** [comment] 2019-02-20 10:18
Thanks a lot for the information @dstine. I tried to circumvent the issue with SFTP and it more or less works. I had to add a config entry for my ssh key though.

Unfortunately my artifacts are not shown in the UI. On the start page of the experiment it says `Artifact Location: sftp://user@host/home/username/mlflow` But when I click on the date of a run I get `Oops, something went wrong...` from mlflow UI. (The tutorials show a nice UI https://www.mlflow.org/docs/latest/tutorial.html of course.)

Does this problem relate to the sftp path?

**Comment by hanyucui** [comment] 2019-03-03 06:33
The artifacts are logged to the URI specified by `--default-artifact-root`. If you pass a local path to it, it will log artifacts to that local path. See [documentation](https://mlflow.org/docs/latest/tracking.html#storage) and #810.

**Comment by SheldonXLD** [comment] 2019-03-08 07:06
I think the logic that store at local is not convincible, because you already have a artifact at local, and in the code just use shutil.copy() to store at another address (same machine).
I think should use the logic same as log_metric that sent rest to remote machine if set_tracking_uri is http and default-artifact-root is None or file path.
Thanks.

**Comment by maoding** [comment] 2019-03-08 10:03
> I think the logic that store at local is not convincible, because you already have a artifact at local, and in the code just use shutil.copy() to store at another address (same machine).
> I think should use the logic same as log_metric that sent rest to remote machine if set_tracking_uri is http and default-artifact-root is None or file path.
> Thanks.

I think that is why I got confused in the first place. I set the remote tracking and thus expect to see all logged items on the remote machine and not locally.

**Comment by Gabriel808** [comment] 2019-03-26 13:00
@maoding 

My team is running into this artifact crashing MLFlow issue as well. We are in an Azure environment using Databricks and Azure Data Lake for artifact storage. Our process is to generating an artifact, store in the Lake, and logging it with log_artifact. When we go back to look at the visuals generated(artifacts), clicking on them brings us to the Niagara Falls error page. Did you all ever find a solution for this?

**Comment by maoding** [comment] 2019-03-28 00:19
Hi @Gabriel808,

I am sorry I think I cannot help you since I haven’t used this in an Azure environment. But I guess setting the right credentials for the store on Azure is essential. Read up on this here https://mlflow.org/docs/latest/tracking.html on the Azure section.

**Comment by mirekphd** [comment] 2019-10-21 12:52
I too think that the behavior of the `log_*` functions is rather inconsistent, without built-in support for uploading larger artifacts such as models to the server side (which is the whole point of experiment tracking - preserve the artifacts to put them in production without refitting). 

For instance H2O uses separate menu options and/or API functions for remote and local actions (download / upload vs import / save). NFS is not remote as it has to be mounted locally on the client side... One needs yet another server apart from mlflow server or else our most important artifacts will be dispersed in local users folders, siloed, passworded, or manually deleted as the ./mflow folder is not even hidden...

Compared to H2O, where one can upload data to a training server and then download trained models from the server, even using a browser, without any scripting (and without having to set up another server such as NFS), remote storage of artifacts in MLflow Tracking is non-existent.

**Comment by teichmaj** [comment] 2019-10-24 08:57
I encountered this problem too. I use many docker containers to run e.g. a Spark environment and a volume to mount the project code into the Spark container. The paths to the mlruns folder are different for the host and the container in consequence. 
Unfortunately, mlflow saves absolute paths in the meta.yaml files and the mlflow never finds the artefacts.
I thought I can fix that with running a central tracking server in a container and log artefacts via the tracking server but the log_model behaviour was not as I expected and I am still looking for a way to use mlflow to manage my artefacts centralised without another sftp server or s3 etc.
I guess there are two issues at least for my use-case:

1. missing http protocol for log_model to upload models to a central tracking server
1. relative paths in meta.yml to share mlruns more easily

**Comment by mirekphd** [comment] 2019-10-26 10:59
> I am still looking for a way to use mlflow to manage my artefacts centralised without another sftp server or s3 etc.

I eventually gave up looking (and you probably should as well:) and embraced the future as envisaged by Databricks - of rampant microservises architecture... It required as many as 3 different servers... and given the one-server-per-container rule, I have 3 containers as well:
1) metrics and params are stored to an SQL database (container 1), and I used MariaDB (`bitnami/mariadb`) - do not skip this one, performance-wise this should be the only option (I ended up increasing worker timeouts to 5 minutes and it was still not enough for default metrics/params storage in text files)!
2) artifacts, including models, are uploaded to an S3 bucket, I used minIO (`bitnami/minio`) 
3) `mflow server` runs in a dedicated container with credentials to both db and S3 (all of which can be parametrized with env vars if you pass them to mlflow at startup in CMD section of your Dockerfile) (`mirekphd/ml-mlflow` - that's a custom one - enjoy:)

What I will have to probably do for security reasons is to add a 4th container with reverse proxy such as `bitnami/nginx` because authorization is another feature missing here... Oh, and I'm not affiliated with Bitnami, it's just that they have constistently hmm, rooted out root from their containers (and so should the official Docker images), so can be run with high UIDs and all capabilities dropped.

**Comment by hossen-code** [comment] 2020-02-21 16:48
in case of writing to files;
`mlflow.set_tracking_uri(f"str(path_to_a_file)")`
worked without the `file:/` as suggested in the documentation of mlflow.

**Comment by erichhuang** [comment] 2020-06-18 14:28
+1

**Comment by dbczumar** [comment] 2020-07-17 07:19
Hi folks, the source of confusion here appears to be the fundamental lack of support for proxying artifact uploads through the MLflow server. We're tracking this issue in #629 and would absolutely welcome designs for this capability. For now, I'm going to close this issue as a duplicate of #629 - please feel free to continue the discussion / contribute implementation ideas there!

**Closed by dbczumar** 2020-07-17 07:19 UTC
Labels: area/artifacts
