### ISSUE TITLE
[FR] Increase Length Limit of 5000

### ISSUE THREAD

**Issue by PhilipMay** [mlflow/mlflow#2892] opened 2020-05-29 07:02 UTC
MLflow seems to have a length limit of 5000 when setting tags (see below).

``` bash
[...]
  File "/home/smay/miniconda3/envs/py38/lib/python3.8/site-packages/mlflow/utils/validation.py", line 136, in _validate_length_limit
    raise MlflowException(
mlflow.exceptions.MlflowException: Tag value '[0.8562690322984875, 0.8544098885636596, 0.8544098885636596, 0.8544098885636596, 0.8544098885636596, 0.859181214773054, 0.86273086038245, 0.86273086038245, 0.86273086038245, 0.86273086038245, 0.86273086038245, 0.8562690322984875, 0.8544098885636596, ' had length 5276, which exceeded length limit of 5000
```
I would like to request if it is possible to increase this limit. Optuna for example does not have this limit when setting user attributes.

If this is not possible for tags: I would like to quest something - maybe new - where it is possible. Placing it into an artefact is to heavy for me...

I am willing to contribute if someone has time to give some hints and is willing to discuss the solution with me.

Thanks
Philip

**Comment by mparkhe** [comment] 2020-05-30 04:02
Hi @PhilipMay : what is your use case that requires tags size > 5000? The thought process behind tags is to save metadata and other custom information that you may want to store on runs. Runs are searchable using tags (among other things). Larger artifacts like models, feature list, attachments that you would not need to search on can be logged as artifacts using [`mlflow.log_artifact`](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_artifact) or [`mlflow.log_artifacts`](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_artifacts)

**Comment by PhilipMay** [comment] 2020-05-30 17:48
> Hi @PhilipMay : what is your use case that requires tags size > 5000? 

Well, in this case it is a list of feature importance values I want to store. IMO the storage of a file (artifact) is too heavyweight. I would like to have something more simple.

I can understand your argument that tags are searchable since this long list will never be filtered after. But nevertheless I would like to have something that can hold this list.

I have written the MLflow integration for Optuna: https://optuna.readthedocs.io/en/latest/reference/integration.html#optuna.integration.MLflowCallback
Here we also come to a situation where Optuna can store things that MLflow can not store (as non artifact).

So when there are no concrete technical limitations please consider to remove this limitation if possible.

**Comment by mparkhe** [comment] 2020-05-30 22:43
Searchability is a key features. Arbitrarily increasing the size of tag values may affect the performance of logging and searching over large values. One of the recommendations would be to  use [plugins to customize some of this functionality](https://mlflow.org/docs/latest/plugins.html) to allow large artifacts to be logged. Another negative of having large blobs logged as tags is increased I/O when searching and listing runs (since the data models pushes all data when a run is fetched).

Furthermore, the UX with large blobs showing up as tags for a run (on run page) or a column on an experiment page needs to be worked out.

While ability to log large data as tags would be nice, the benefit of having this large data blob stored as tag vs artifact is not clear. Here are a couple of alternatives to be able to do achieve what you are trying to do.

### Log each feature importance value as a tag (or metric)
```
for (feature_name, importance_value) in features.items():
  key = "feature_importance.{}".format(feature_name)
  mlflow.log_metric(key, importance_value)
```
This will make searchability using a specific feature value and importance (`"metrics.feature_importance.sq_footage > 0.45"`) or order runs based on feature importance like

```
search_runs(filter = "metrics.error_rate < 0.2 AND params.model_type = 'tensorflow'",
            order_by = ["metrics.feature_importance.sq_footage", "metrics.feature_importance.inventory DESC"])
```

### As recommended before log the entire feature blob as an artifact
You can create a handy function log features
```
def log_feature(features):
    with TempDir() as tmp:
        feature_path = tmp.path("features.csv")
        with open(feature_path, "w") as writer:
            data = "\n".join("{},{}".format(k, v) for (k, v) in sorted(features.items()))
            writer.write(data)
        mlflow.log_artifact(feature_path)
```
This has a benefit of being stored with the run and unlike tags cannot be overwritten.

I am closing this issue out as a duplicate of #2173

**Closed by mparkhe** 2020-05-30 22:43 UTC
Labels: enhancement

**Comment by PhilipMay** [comment] 2020-06-08 19:50
Ok. Thanks for your explanation.
