### ISSUE TITLE
[FR] Implement delete registered model version in MLflow UI

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#6068] opened 2022-06-15 19:34 UTC
### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

 1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Describe the problem

There is no button to delete a registered model version in the UI.

### Steps to reproduce the bug

Just look at the UI page for model version.

**Comment by dbczumar** [comment] 2022-06-15 21:05
@amesar Can you convert this to a feature request? The absence of a feature is not a bug.

**Comment by subramaniam02** [comment] 2022-06-16 00:21
@dbczumar I willing to contribute. Can you please assign this to me ?

**Comment by dbczumar** [comment] 2022-06-16 00:34
@subramaniam02 Fantastic! I've assigned this issue to you. Thank you in advance for your contribution!

**Comment by subramaniam02** [comment] 2022-06-16 05:54
This ask is an already existing feature in mlflow. Here are the screenshots. maybe we can enhance the visibility of the three dots menu on far right.

<img width="1674" alt="Screen Shot 2022-06-15 at 10 44 28 PM" src="https://user-images.githubusercontent.com/1637727/174000079-e2f494e2-2e84-4754-8fd0-08dcb56c5376.png">

<img width="1674" alt="Screen Shot 2022-06-15 at 10 44 28 PM" src="https://user-images.githubusercontent.com/1637727/174001145-0acc0da3-597d-4e89-9e46-a212dfe3c553.png">


<img width="1674" alt="Screen Shot 2022-06-15 at 10 46 28 PM" src="https://user-images.githubusercontent.com/1637727/174000126-e5396312-a178-46f8-a38e-b7f0afc07b3d.png">

**Comment by dbczumar** [comment] 2022-08-12 20:14
Thanks @subramaniam02 !

**Closed by dbczumar** 2022-08-12 20:14 UTC
Labels: enhancement, area/uiux, help wanted
