### ISSUE TITLE
[BUG] can't run MLFlow project on Windows

### ISSUE THREAD

**Issue by mrmutator** [mlflow/mlflow#1670] opened 2019-07-26 13:46 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **MLflow installed from (source or binary)**:  pip install mlflow in conda environmnet
- **MLflow version (run ``mlflow --version``)**: 1.1.0
- **Python version**:  3.7.3
- **npm version, if running the dev UI**:
- **Exact command to reproduce**: mlflow run <git-repository>

### Describe the problem
When running the command `mlflow run <git-repository>` for a project that uses a conda environment, the project can't be run because of a _FileNotFoundError: [WinError 2] The system cannot find the file specified_ error.

### Logs
`2019/07/26 14:57:50 INFO mlflow.projects: === Running command 'source C:\Users\myUser\AppData\Local\Continuum\anaconda3\Scripts/../etc/profile.d/conda.sh && conda activate mlflow-5704e62345c83aec63a905fd394fede4b904cc8d 1>&2 && python run.py in run with ID '2115ac6375394aaea8a22376b81b1ee3' ===`

Running the project fails because the command "source" is not available on Windows. The bug might have been introduced in #1576.

**Comment by aarondav** [comment] 2019-07-26 21:56
Ah, did we complete `model run` support on Windows @akshaya-a? I know we support the tracking server, but I'm not sure if conda-backed project running is expected to work.

You should be able to activate the conda environment manually and run this with `--no-conda`, at least.

**Comment by zach-merritt** [comment] 2019-07-29 18:51
I've experienced the same thing for `mlflow ui`

**Comment by bezova** [comment] 2019-07-31 22:33
same issue for me

**Comment by ZainNasrullah** [comment] 2019-08-02 19:23
Everything works fine in mlflow 1.0.0, updating to 1.1.0 seems to introduce this issue

**Comment by abhirus** [comment] 2019-09-18 10:07
This issue is noticed in latest 1.2 version as well. Do we have any workaround or fix for samee?

**Comment by abhirus** [comment] 2019-09-18 10:11
With mlflow 1.2 and Python 3.7 and trying to run multistep_workflow project from examples git and getting the below error

2019/09/18 15:30:53 INFO mlflow.projects: === Running command 'source C:\Program Files\miniconda3\Scripts/../etc/profile.d/conda.sh && conda activate mlflow-3523e1f70a6145c6a0cd1705275ffde004dc1f47 1>&2 && python main.py --als-max-iter 10 --keras-hidden-units 20 --max-row-limit 100000' in run with ID 'badc8f57f5f0486db7fc0bcd64b3b247' ===
Traceback (most recent call last):
  File "C:\Software\Python\3_7\Scripts\mlflow-script.py", line 11, in <module>
    load_entry_point('mlflow==1.2.0', 'console_scripts', 'mlflow')()
  File "c:\software\python\3_7\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
......
......
......
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by davidbeaudoin** [comment] 2019-10-07 16:41
Same problem with mlflow 1.2 and Python 3.7 when I am trying to run examples.

mlflow run examples/sklearn_elasticnet_wine -P alpha=0.5

OR

mlflow run  https://github.com/amesar/mlflow-fun.git#examples/hello_world -Palpha=100 -Prun_origin=GitRun -Plog_artifact=True

I get...

2019/10/07 12:32:38 INFO mlflow.projects: === Running command 'source C:\Users\xyz\AppData\Local\Continuum\anaconda3\condabin\..\Scripts/../etc/profile.d/conda.sh && conda activate mlflow-3aa2780eca4cae76d732f52fb1221a37080b256f 1>&2 && python hello_world.py
100 GitRun True' in run with ID 'a810fb60e48d46cab0e88513405c2e4b' ===

Traceback (most recent call last):
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\Scripts\mlflow-script.py", line 11, in <module>
    load_entry_point('mlflow==1.3.0', 'console_scripts', 'mlflow')()
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\mlflow\cli.py", line 137, in run
    run_id=run_id
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\mlflow\projects\__init__.py", line 285, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\mlflow\projects\__init__.py", line 173, in _run
    run_id=active_run.info.run_id)
  File "C:\Users\xyz\PycharmProjects\mlflow\venv\lib\site-packages\mlflow\projects\__init__.py", line 575, in _run_entry_point
    process = subprocess.Popen(command, close_fds=True, cwd=work_dir, env=env)
  File "C:\Users\xyz\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\xyz\AppData\Local\Continuum\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by katielaines** [comment] 2019-10-08 21:35
Getting same error today when serving model

>_mlflow models serve -m runs:/b2de9128f8764d81b7cb452e2c69329f/model_

> 
> 
> 2019/10/08 17:29:48 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
> 2019/10/08 17:29:49 INFO mlflow.pyfunc.backend: === Running command 'source C:\Users\xyz\AppData\Local\Continuum\miniconda3\Scripts/../etc/profile.d/conda.sh && conda activate mlflow-41d4474c41caf84e922effe9e3fc9d76e7ffbf38 1>&2 && gunicorn --timeout=60 -b 127.0.0.1:5000 -w 1 ${GUNICORN_CMD_ARGS} -- mlflow.pyfunc.scoring_server.wsgi:app'
> Traceback (most recent call last):
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\xyz\AppData\Local\Continuum\miniconda3\Scripts\mlflow.exe\__main__.py", line 9, in <module>
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\xxyz\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\site-packages\mlflow\models\cli.py", line 56, in serve
>     host=host)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\site-packages\mlflow\pyfunc\backend.py", line 77, in serve
>     command_env=command_env)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\site-packages\mlflow\pyfunc\backend.py", line 142, in _execute_in_conda_env
>     child = subprocess.Popen(["bash", "-c", command], close_fds=True, env=command_env)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "c:\users\xyz\appdata\local\continuum\miniconda3\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)
> **FileNotFoundError: [WinError 2] The system cannot find the file specified**

**Comment by Gondal-SaadAbdullah** [comment] 2019-10-26 16:38
I am getting while running: examples/hyperparam
Do we have a solution for that? Or is there any other branch where we have a runnable build?

**Comment by dol0828** [comment] 2019-10-30 13:02
Exactly the same issue. Really want to try it in my Windows workstation, and hope it will be fixed shortly. Thanks.

**Comment by simonkwok2000** [comment] 2019-12-03 08:37
With mlflow 1.4.0, python 3.6 and conda 4.7.12, this issue can be fixed by changing this line in the source code.
File mlflow\projects\__init__.py, line 687
`return ["conda.bat activate %s" % (conda_env_name)]`
Windows CreateProcess could not find the file conda because it actually points to conda.bat in an Anaconda prompt.

**Comment by HugangRen** [comment] 2019-12-18 00:10
This worked for me. Can someone incorporate this change in MLFlow package?
> With mlflow 1.4.0, python 3.6 and conda 4.7.12, this issue can be fixed by changing this line in the source code.
> File mlflow\projects__init__.py, line 687
> `return ["conda.bat activate %s" % (conda_env_name)]`
> Windows CreateProcess could not find the file conda because it actually points to conda.bat in an Anaconda prompt.

**Comment by SebastianScherer88** [comment] 2020-01-20 15:36
> With mlflow 1.4.0, python 3.6 and conda 4.7.12, this issue can be fixed by changing this line in the source code.
> File mlflow\projects__init__.py, line 687
> `return ["conda.bat activate %s" % (conda_env_name)]`
> Windows CreateProcess could not find the file conda because it actually points to conda.bat in an Anaconda prompt.

For MLFlow 1.5, the change is in line 620 - it's the same 'get_conda_command' function again. that should be a quick PR to fix?

**Comment by chinwobble** [comment] 2020-02-26 10:55
bump still getting this in mlflow 1.6
```
2020/02/26 21:51:31 INFO mlflow.projects: === Running command 'conda activate mlflow-394111e2a63ae021816efb57c1bd5a286db85045 && python train.py 0.5 0.1' in run with ID '73e7f6c5454a4e6aadc8ec6523b33afe' ===
Traceback (most recent call last):
  File "c:\tools\miniconda3\envs\py35mlflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\tools\miniconda3\envs\py35mlflow\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\mlflow\cli.py", line 134, in run
    run_id=run_id
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\mlflow\projects\__init__.py", line 288, in run
    use_conda=use_conda, storage_dir=storage_dir, synchronous=synchronous, run_id=run_id)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\mlflow\projects\__init__.py", line 171, in _run
    run_id=active_run.info.run_id)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\site-packages\mlflow\projects\__init__.py", line 510, in _run_entry_point
    process = subprocess.Popen(command, close_fds=True, cwd=work_dir, env=env)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\tools\miniconda3\envs\py35mlflow\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

(py35mlflow) C:\dev\mkflow-example>mlflow run mlflow-example -P alpha=0.5 --no-conda
2020/02/26 21:52:07 INFO mlflow.projects: === Created directory C:\Users\benne\AppData\Local\Temp\tmpm0ugqa_p for downloading remote URIs passed to arguments of type 'path' ===
2020/02/26 21:52:07 INFO mlflow.projects: === Running command 'python train.py 0.5 0.1' in run with ID 'c8c9f66f88d34e8d87799c4718f1d9e7' ===
Traceback (most recent call last):
  File "train.py", line 11, in <module>
    from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
ModuleNotFoundError: No module named 'sklearn'
2020/02/26 21:52:07 ERROR mlflow.cli: === Run (ID 'c8c9f66f88d34e8d87799c4718f1d9e7') failed ===
```

**Comment by bhushanbrb** [comment] 2021-01-24 03:37
On MacOS : 
Step1 ) mlflow run https://github.com/mlflow/mlflow-example.git -P alpha=5.0
Step2) mlflow models serve -m runs:/336da3da482d4b8a898ca4da84729075/model   

Errors out with 
ModuleNotFoundError: No module named 'sklearn.linear_model.coordinate_descent'

**Comment by chandrakanthpuvvada** [comment] 2021-02-19 04:56
**mlflow models serve -m runs:/74b0dadee65644488c432981f75865dc/model --port 1234 --no-conda execution failed with**

> FileNotFoundError: [WinError 2] The system cannot find the file specified

In local windows machine this issue is fixed for  **--no-conda** execution.

**File name: mlflow\pyfunc\backend.py**
**Class name:PyFuncBackend**
**Function:serve**

 **Original Line**
> subprocess.Popen([command.split(" ")], env=command_env).wait()

**changed to** 

> **subprocess.Popen(command.split(" "), env=command_env).wait()**

**root cause:**
**Issue is array of array**
command.split(" ") this will return array[] but passing **subprocess.Popen(**[[]]**, env=command_env).wait()**.
When remove outer array started working for  --no-conda 
**following command working fine:**

**models serve -m runs:/74b0dadee65644488c432981f75865dc/model --port 1234 --no-conda** 




### **Steps to reproduce the issue:**

On Windows: 
mlflow version:1.13.1
OS: Windows 10
Step 1) **mlflow run . -P alpha=0.42 --no-conda  executed successfully.**
Step 2): **mlflow models serve -m runs:/74b0dadee65644488c432981f75865dc/model --port 1234 --no-conda execution failed.**

ERROR:
FileNotFoundError: [WinError 2] The system cannot find the file specified

Exception:

2021/02/18 12:34:08 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2021/02/18 12:34:08 INFO mlflow.pyfunc.backend: === Running command 'waitress-serve --host=127.0.0.1 --port=1234 --ident=mlflow mlflow.pyfunc.scoring_server.wsgi:app'
Traceback (most recent call last):
  File "c:\users\userappdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\userappdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\userAppData\Local\Programs\Python\Python37\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\mlflow\models\cli.py", line 57, in serve
    ).serve(model_uri=model_uri, port=port, host=host)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\mlflow\pyfunc\backend.py", line 99, in serve
    subprocess.Popen([command.split(" ")], env=command_env).wait()
  File "c:\users\userappdata\local\programs\python\python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "c:\users\userappdata\local\programs\python\python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by chandrakanthpuvvada** [comment] 2021-02-19 05:10
**mlflow models serve -m runs:/74b0dadee65644488c432981f75865dc/model --port 1234 --no-conda execution failed with**

> FileNotFoundError: [WinError 2] The system cannot find the file specified

In local windows machine this issue is fixed for  **--no-conda** execution.

**File name: mlflow\pyfunc\backend.py**
**Class name:PyFuncBackend**
**Function:serve**

 **Original Line**
> subprocess.Popen([command.split(" ")], env=command_env).wait()

**changed to** 

> **subprocess.Popen(command.split(" "), env=command_env).wait()**

**root cause:**
**Issue is array of array**
command.split(" ") this will return array[] but passing **subprocess.Popen(**[[]]**, env=command_env).wait()**.
When remove outer array started working for  --no-conda 
**following command working fine:**

**models serve -m runs:/74b0dadee65644488c432981f75865dc/model --port 1234 --no-conda** 




### **Steps to reproduce the issue:**

On Windows: 
mlflow version:1.13.1
OS: Windows 10
Step 1) **mlflow run . -P alpha=0.42 --no-conda  executed successfully.**
Step 2): **mlflow models serve -m runs:/74b0dadee65644488c432981f75865dc/model --port 1234 --no-conda execution failed.**

ERROR:
FileNotFoundError: [WinError 2] The system cannot find the file specified

Exception:

2021/02/18 12:34:08 INFO mlflow.models.cli: Selected backend for flavor 'python_function'
2021/02/18 12:34:08 INFO mlflow.pyfunc.backend: === Running command 'waitress-serve --host=127.0.0.1 --port=1234 --ident=mlflow mlflow.pyfunc.scoring_server.wsgi:app'
Traceback (most recent call last):
  File "c:\users\userappdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\userappdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\userAppData\Local\Programs\Python\Python37\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\mlflow\models\cli.py", line 57, in serve
    ).serve(model_uri=model_uri, port=port, host=host)
  File "c:\users\userappdata\local\programs\python\python37\lib\site-packages\mlflow\pyfunc\backend.py", line 99, in serve
    subprocess.Popen([command.split(" ")], env=command_env).wait()
  File "c:\users\userappdata\local\programs\python\python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "c:\users\userappdata\local\programs\python\python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by dbczumar** [comment] 2022-06-02 00:56
Given that the problem appears to have been addressed, I'm going to go ahead and close this issue. Please feel free to reopen it if it continues to occur.

**Closed by dbczumar** 2022-06-02 00:56 UTC
Labels: bug, area/windows, Acknowledged, area/projects, priority/important-soon

**Comment by michalisfrangos** [comment] 2023-02-14 12:47
Hi all,  hi @dbczumar .

still getting this in mlflow 2.1.1 (Python 3.9.15, Windows 11 Pro, mlflow Version: 2.1.1.). 

Is this still a known issue? The solution suggested is not clear to me from the discussions above. Any ideas?


ERROR
--------
`Traceback (most recent call last):
  File 
"C:\Users\m\miniconda3\envs\env_explore\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,    
  File "C:\Users\m\miniconda3\envs\env_explore\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\m\miniconda3\envs\env_explore\Scripts\mlflow.exe\__main__.py", line 7, in <module>
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\mlflow\cli.py", line 201, in run
    projects.run(
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\mlflow\projects\__init__.py", line 329, in run
    submitted_run_obj = _run(
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\mlflow\projects\__init__.py", line 102, in _run
    submitted_run = backend.run(
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\mlflow\projects\backend\local.py", line 77, in run
    work_dir = fetch_and_validate_project(project_uri, version, entry_point, params)
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\mlflow\projects\utils.py", line 137, in fetch_and_validate_project
    work_dir = _fetch_project(uri=uri, version=version)
  File "C:\Users\m\miniconda3\envs\env_explore\lib\site-packages\mlflow\projects\utils.py", line 109, in _is_local_uri
    resolved_uri = pathlib.Path(_parse_file_uri(uri)).resolve()
  File "C:\Users\m\miniconda3\envs\env_explore\lib\pathlib.py", line 1215, in resolve
    s = self._flavour.resolve(self, strict=strict)  File "C:\Users\m\miniconda3\envs\env_explore\lib\pathlib.py", line 215, in resolve    s = self._ext_to_normal(_getfinalpathname(s))

OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https:\\github.com\\mlflow\\mlflow-example.git`

**Comment by BalHelmi** [comment] 2023-08-06 21:25
Hello @michalisfrangos , did you fixed that error , please help me with the solution .

**Comment by Istr8** [comment] 2024-05-18 19:57
i think it interpreates the github link as a local uri, because the function checks _is_local_uri method, not _is_github_repo

**Comment by stevem995** [comment] 2025-03-18 19:23
Seeing this on Windows 11, python 3.9.9, mflow version 2.21.0 using both ssh and https. 
python -m mlflow run 'git@github.com:mlflow/mlflow-example.git' -P alpha=5
  File "\.pyenv\pyenv-win\versions\3.9.9\lib\pathlib.py", line 215, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'git@github.com:mlflow\\mlflow-example.git'
