### ISSUE TITLE
[BUG] API doesn't accept params/metrics that are empty strings

### ISSUE THREAD

**Issue by prafiny** [mlflow/mlflow#6066] opened 2022-06-15 15:32 UTC
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.26.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker : python:3.10/archlinux
- **Python version**: 3.10/3.9
- **yarn version, if running the dev UI**: N/A

### Describe the problem

When logging params and possibly metrics among which there are empty strings, the following error occurs:
```
echo -n '{"run_id": "573dfa71adf94a1ca1c11b27e216a372", "params": [{"key": "save_strategy", "value": ""}]}' | http POST http://127.0.0.1:5000/api/2.0/mlflow/runs/log-batch
HTTP/1.1 400 BAD REQUEST
Connection: close
Content-Length: 238
Content-Type: application/json
Date: Wed, 15 Jun 2022 15:26:18 GMT
Server: gunicorn

{
    "error_code": "INVALID_PARAMETER_VALUE",
    "message": "Invalid value [{'key': 'save_strategy', 'value': ''}] for parameter 'params' supplied. Hint: Value was of type 'list'. See the API docs for more information about request parameters."
}
```

It should log the batch as is.

### Tracking information

```bash
mlflow server
```

### Code to reproduce issue

Working example:
```bash
echo -n '{"run_id": "573dfa71adf94a1ca1c11b27e216a372", "params": [{"key": "save_strategy", "value": "epoch"}]}' | http POST http://127.0.0.1:5000/api/2.0/mlflow/runs/log-batch
```

Non-working example:
```bash
echo -n '{"run_id": "573dfa71adf94a1ca1c11b27e216a372", "params": [{"key": "save_strategy", "value": ""}]}' | http POST http://127.0.0.1:5000/api/2.0/mlflow/runs/log-batch
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [X] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment] 2022-06-15 23:32
Duplicate of https://github.com/mlflow/mlflow/issues/6027.

**Closed by harupy** 2022-06-15 23:32 UTC
Labels: bug, area/tracking
