### ISSUE TITLE
[BUG] Failing to download large artifacts through mlflow dashboard

### ISSUE THREAD

**Issue by sniafas** [mlflow/mlflow#6331] opened 2022-07-26 12:46 UTC
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.26

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu Server 20.04 
- **Python version**: 3.8
- **yarn version, if running the dev UI**:

### Describe the problem

Not sure if this is a bug. Downloading large experimental artifacts (500MB) through mlflow dashboard is failing leading to an nginx 502 bad gateway.
I am using an mlflow server instance with an nginx as a reverse proxy on a domain.
Not sure if this is a bug or a missing configuration in nginx. Any other minimal file is downloading fine.

### Code to reproduce issue

N/A

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment] 2022-07-26 19:22
Hi @sniafas, do you have any stacktrace information available from the server when the download(s) time out? This will help determine the cause of the issue. Are you running your MLflow server in `--serve-artifacts` mode?

**Comment by sniafas** [comment] 2022-07-27 11:20
Hi @dbczumar, 
MLflow server runs with a `--backend-store-uri` with postgres and a `--default-artifact-root` pointing an `s3` bucket. It has 2G of ram but does not seem to run out when attempting download. 

This is the available stacktrace. Does this help?
```
[2022-07-27 14:12:27 +0300] [3348435] [CRITICAL] WORKER TIMEOUT (pid:1280491)
[2022-07-27 14:12:28 +0300] [1280491] [INFO] Worker exiting (pid: 1280491)
[2022-07-27 14:12:28 +0300] [3348435] [WARNING] Worker with pid 1280491 was terminated due to signal 9
[2022-07-27 14:12:28 +0300] [1435231] [INFO] Booting worker with pid: 1435231
```

**Comment by dbczumar** [comment] 2022-07-27 21:59
@sniafas Got it. Seems like the issue can be resolved by increasing the timeout of the gunicorn workers used by `mlflow server` to process requests. By default, the timeout is 30 seconds. You can increase it via:

```
mlflow server --gunicorn-opts "-t 120"
```

This will set the timeout to 120 seconds; you can configure the timeout as needed.

I'm going to go ahead and close this issue; please let me know if this adjustment does not resolve the problem, and I will reopen the issue. Thank you for using MLflow!

**Closed by dbczumar** 2022-07-27 21:59 UTC
Labels: bug, area/artifacts, area/model-registry

**Comment by pascalwhoop** [comment] 2024-08-27 10:24
> --gunicorn-opts "-t 120

when running with argocd/helm we had to

```
mlflow:
  tracking:
    extraArgs:
      - '--gunicorn-opts="-t 360"'
 ```
