### ISSUE TITLE
Error when run server using db backend

### ISSUE THREAD

**Issue by DAEHEESHIN** [mlflow/mlflow#1419] opened 2019-06-07 07:15 UTC
### System information
linux, python 3.6

### Describe the problem
when i run server.. if i have password that contains '!'...
i make error follwing
'-bash: !@host: event not found'

mlflow server --backend-store-uri mysql://id:pw1!@host:3306/mlflow --default-artifact-root hdfs://:host:50070/data/pay_model/ --host 0.0.0.0

**Comment by DAEHEESHIN** [comment] 2019-06-07 07:41
sorry~! i solve with changing pw1! ->  'pw1!'

**Comment by smurching** [comment] 2019-06-12 02:43
Glad you were able to find a fix @DAEHEESHIN, will close this for now.

**Closed by smurching** 2019-06-12 02:43 UTC

**Comment by yuviabhi** [comment] 2022-06-01 05:56
Still giving error when the password is Redhat@321#

`mlflow server --backend-store-uri mysql://id:Redhat@321#@host:3306/mlflow --default-artifact-root hdfs://:host:50070/data/pay_model/ --host 0.0.0.0`

The fix with single quote `'Redhat@321#'`  is not working.
Actually the problem is with @ inside the password. 
Any bypass for this ?
