### ISSUE TITLE
[BUG] mlflow.sklearn.log_model does not log any model to the artifact section to register.

### ISSUE THREAD

**Issue by mk2s6** [mlflow/mlflow#2421] opened 2020-02-12 04:32 UTC
As this is my following code as mentioned in the documentation and yet it does not work accordingly. and doesnot log any model to the artifacts page.

import mlflow
import joblib
import mlflow.sklearn
from mlflow.models import Model
mlflow.set_tracking_uri("http://localhost:5000")

from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()

experiment_name = "Test1"
print("MLflow Version:",mlflow.version.VERSION)
mlflow.set_experiment(experiment_name)
mlflow_client = mlflow.tracking.MlflowClient()
experiment_id = mlflow_client.get_experiment_by_name(experiment_name).experiment_id
print("experiment_id:",experiment_id)
print("experiment_name:",experiment_name)

with mlflow.start_run() as run:
    print(run.info.run_uuid)
    sk_model = tree.DecisionTreeClassifier()
    sk_model = sk_model.fit(iris.data, iris.target)
    #set the artifact_path to location where experiment artifacts will be saved
    #log model params
    mlflow.log_param("criterion", sk_model.criterion)
    mlflow.log_param("splitter", sk_model.splitter)
    #log model
    mlflow.log_metric("Acc ", 78)
    mlflow.log_metric("Test", 98)
    # mlflow.sklearn.save_model(sk_model, "sk_models1")

    # Model.log(artifact_path="sk_models", flavor=mlflow.sklearn, sk_model=sk_model, conda_env = None, serialization_format = 'pickle', registered_model_name = None)
    # joblib.dump(sk_model, 'iris.model')
    mlflow.sklearn.log_model(sk_model, "model")
    # mlflow.register_model(model_uri='sk_models', name="model1")

**Comment by mk2s6** [comment] 2020-02-12 05:01
![Uploading Screenshot (2).png…]()

**Comment by msabramo** [comment] 2020-02-21 01:21
I was seeing some behavior like this where my models were not showing up on the tracking server and I discovered that the model artifacts were stored locally rather than on the server. I don't know if this is the intended behavior or not?

**Comment by msabramo** [comment] 2020-02-21 01:22
#2215 might be relevant?

**Comment by mk2s6** [comment] 2020-02-28 04:49
No, It does not help it.

**Comment by delcacho** [comment] 2020-04-14 11:11
I am having a similar issue, probably retaled.

Remote tracker running in a server, with PostgreSQL as backend. Artifact storage in S3.

log_model stores correctly the artifact in S3, but when I go and try to access it in the Tracking server, it says no artifact is available.

**Comment by harupy** [comment] 2020-08-05 10:46
@mk2s6 How did you launch the MLflow UI?

**Comment by mk2s6** [comment] 2020-08-05 11:03
> @mk2s6 How did you launch the MLflow UI?

@harupy Do check in Command Line options -  To Start MLFLOW UI You need to run command **`mlflow ui`** command in terminal or cmd or any other command line applications, That will get your UI opened on a new browser window.

**Comment by harupy** [comment] 2020-08-05 11:13
@mk2s6 Thanks. Are you still experiencing this issue?

**Comment by mk2s6** [comment] 2020-08-05 11:20
> @mk2s6 Thanks. Are you still experiencing this issue?

@harupy No we don't see this issue currently, and also we use it with Databricks currently, so we don't see this issue now.

**Comment by harupy** [comment] 2020-08-05 11:20
@mk2s6 Cool. Can I close this issue?

**Comment by mk2s6** [comment] 2020-08-05 11:34
@harupy  Yes. You Can. Thank You

**Closed** 2020-08-05 11:34 UTC
Labels: area/artifacts, area/models, bug, priority/important-soon
