### ISSUE TITLE
[BUG] Lazy load issue with tensorflow

### ISSUE THREAD

**Issue by yalwan-sage** [mlflow/mlflow#10472] opened 2023-11-21 15:32 UTC
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

- Client: 2.8.1
- Tracking server: 2.8.1

### System information

Python 3.11
Linux

### Describe the problem

When importing MLFlow, one can reference certain submodules referring to an ML framework without having them instakked

e.g. `mlflow.sklearn`, `mlflow.pytorch` `mlflow.tensorflow`

however, with `mlflow.tensorflow` the error `ModuleNotFoundError: No module named 'tensorflow'` occurs; it seems MLFlow has broken lazy loading for the tensorflow module.

### Code to reproduce issue

```python
import mlflow
mlflow.tensorflow
```

### Stack trace

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 310, in _module_repr
  File "/home/yaxattax/mlflow_repro/lib/python3.11/site-packages/mlflow/utils/lazy_load.py", line 41, in __getattr__
    module = self._load()
             ^^^^^^^^^^^^
  File "/home/yaxattax/mlflow_repro/lib/python3.11/site-packages/mlflow/utils/lazy_load.py", line 30, in _load
    module = importlib.import_module(self.__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/yaxattax/mlflow_repro/lib/python3.11/site-packages/mlflow/tensorflow/__init__.py", line 35, in <module>
    from mlflow.tensorflow.callback import MLflowCallback  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaxattax/mlflow_repro/lib/python3.11/site-packages/mlflow/tensorflow/callback.py", line 1, in <module>
    from tensorflow import keras
ModuleNotFoundError: No module named 'tensorflow'
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/gateway`: AI Gateway service, Gateway client APIs, third-party Gateway integrations
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by WeichenXu123** [comment] 2023-11-22 02:17
Thanks for reporting this ! Checking..

**Comment by harupy** [comment] 2023-11-22 02:28
@yalwan-sage are you sure tensorflow is installed?

**Comment by WeichenXu123** [comment] 2023-11-22 02:35
If tensorflow is installed, we don't have the error.

But shall we allow using `mlflow.tensorflow` in code when tensorflow is not installed ?

**Comment by WeichenXu123** [comment] 2023-11-22 02:41
I think this is a trivial issue . If tensorflow is not installed, using `mlflow.tensorflow` in your code is meaningless

**Comment by yalwan-sage** [comment] 2023-11-23 08:09
Up until some recent version this was not causing an issue.

I'd like to note that referencing any other module like this doesn't cause full imports of the underlying module in case they're not installed.

As noted in the issue, `mlflow.pytorch` does not cause pytorch to load (or attemp to be loaded)

> @yalwan-sage are you sure tensorflow is installed?

It isn't, and  thats entirely the point. But neither is pytorch. 



> I think this is a trivial issue . If tensorflow is not installed, using `mlflow.tensorflow` in your code is meaningless

I disagree. anyone who might create some pre-references to these objects, for example in producing wrappers of some kind (as we are) would be affected by this change in behaviour; it also violates the principle of least surprise; I don't expect to made a module reference and simply referencing the module causes an import action of other modules. I want to reiterate that this didn't used to be the case.

**Comment by WeichenXu123** [comment] 2023-11-23 08:24
You can make `mlflow.tensorflow.MLflowCallback` to be lazily imported to address the issue.
https://github.com/mlflow/mlflow/blob/70e72373f494a39fed5d131ec053833a34bc3cdc/mlflow/tensorflow/__init__.py#L35

Note mlflow.keras_core has similar issue because of the same reason.

**Comment by yalwan-sage** [comment] 2023-11-23 08:29
This doesn't work; i cant reference `mlflow.tensorflow` so how can i reference `mlflow.tensorflow.callback`?

**Comment by WeichenXu123** [comment] 2023-11-23 10:41
@yalwan-sage I created a PR to fix this, you could try: `pip install git+https://github.com/WeichenXu123/mlflow.git@tf-lazy-loading`

**Comment by yalwan-sage** [comment] 2023-11-23 11:27
Yep that works nicely

```
>>> import mlflow
>>> mlflow.pytorch
<module 'mlflow.pytorch (Not loaded yet)'>
>>> mlflow.tensorflow
<module 'mlflow.tensorflow (Not loaded yet)'>
>>> 
```

I like the (Not loaded yet) too in the repr 😁 

I appreciate the effort to this. Could you give an estimate when you think this fix might appear in a release (if it will make it in)?

**Comment by yalwan-sage** [comment] 2023-11-23 14:15
Actually it still causes an issue for us with how we define it; we use an enum to point at the various submodules

curiously enough, defining a dict in global scope with the values as the mlflow modules does not cause this error.

**Comment by WeichenXu123** [comment] 2023-11-24 09:23
> we use an enum to point at the various submodules

Could you share code ? I can help checking it.

**Comment by yalwan-sage** [comment] 2023-11-24 10:12
something simple like this:

```python
import enum

class demo(enum.Enum):
    tensorflow = mlflow.tensorflow
```

**Comment by WeichenXu123** [comment] 2023-11-24 11:03
Because `enum` will check field whether is "descriptor", this requires to check attribute in the object:

```
def _is_descriptor(obj):
    """
    Returns True if obj is a descriptor, False otherwise.
    """
    return (
            hasattr(obj, '__get__') or
            hasattr(obj, '__set__') or
            hasattr(obj, '__delete__')
            )
```

But I think overwrite `hasattr` for the module object is risky. Otherwise, we have to load the module then we know its attribute.

**Comment by WeichenXu123** [comment] 2023-11-24 11:05
I think you can write
```
>>> class AA:
...     tf = mlflow.tensorflow
```
instead of using enum

**Comment by yalwan-sage** [comment] 2023-11-24 11:08
I take your point, but I think the bigger point here is that the `mlflow.tensorflow` module is doing something differently than all the others that it can trigger an eager load unintentionally, and I'd suggest that should probably be addressed? I'm not sure what the root cause is for it to be different from the other modules.

**Comment by WeichenXu123** [comment] 2023-11-24 11:10
> mlflow.tensorflow module is doing something differently than all the others 

Yes. `mlflow.tensorflow` have to import the "MlflowMLflowCallback` , and `MlflowMLflowCallback` inherits `keras.callbacks.Callback` so it has to import tensorflow when importing `MlflowMLflowCallback`

`mlflow.keras_core` has the same issue

**Comment by WeichenXu123** [comment] 2023-11-27 03:50
PR is merged. https://github.com/mlflow/mlflow/pull/10494 You can wait next mlflow release. :)

**Closed by WeichenXu123** 2023-11-27 03:50 UTC
Labels: bug

**Comment by praateekmahajan** [comment] 2024-01-26 22:12
@WeichenXu123 I'm not entirely sure if this is the same but we are seeing a similar issue to do with lazy loading and `keras_core` even though our code doesn't use anything keras / tensorflow. We are on `mlflow 2.9.2`, and `importlib-metadata/resources 5.2.0` and `cloudpickle 2.2.1`

```python
  File "/usr/local/lib/python3.9/site-packages/cascade/executors/vertex/executor.py", line 164, in _stage
    cloudpickle.dump(job, f)
  File "/usr/local/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 55, in dump
    CloudPickler(
  File "/usr/local/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
  File "/usr/local/lib/python3.9/site-packages/mlflow/utils/lazy_load.py", line 41, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.9/site-packages/mlflow/utils/lazy_load.py", line 30, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/mlflow/keras_core/__init__.py", line 1, in <module>
    from mlflow.keras_core.callback import MLflowCallback
  File "/usr/local/lib/python3.9/site-packages/mlflow/keras_core/callback.py", line 1, in <module>
    import keras_core as keras
ModuleNotFoundError: No module named 'keras_core'

```

**Comment by WeichenXu123** [comment] 2024-01-29 09:49
@praateekmahajan Could you create a new ticket  with reproducing code ? It might be a bit different. We have fixed the lazily load module issue .
