### ISSUE TITLE
[FR] Implement OR operator for search methods

### ISSUE THREAD

**Issue by amesar** [mlflow/mlflow#6479] opened 2022-08-16 04:16 UTC
### Willingness to contribute

Yes. I would be willing to contribute this feature with guidance from the MLflow community.

### Proposal Summary

OR is a standard search operator that is needed for efficient searches for a list of objects. We need the filtering to be done on the server side, not the client side since it wouldn't scale in the latter.

For example, "name = 'sklearn_wine' OR name = 'sklearn_iris' ".

Even better would be an IN clause as in "name in ['sklearn_wine', 'sklearn_iris']"

### Motivation

> #### What is the use case for this feature?

If I want to retrieve two MLflow objects (e.g. experiments) with a search. Basic search functionality.

For example, if I have 2000 experiments, I want the server just to send me two experiments.

> #### Why is this use case valuable to support for MLflow users in general?

> #### Why is this use case valuable to support for your project(s) or organization?

> #### Why is it currently difficult to achieve this use case?

I have to retrieve all MLflow objects on the client side, and then filter out the ones I want.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment] 2022-08-16 04:20
Duplicate of https://github.com/mlflow/mlflow/issues/6075

**Closed** 2022-08-16 23:32 UTC
Labels: enhancement
