### ISSUE TITLE
MLflow worker timeout when opening UI

### ISSUE THREAD

**Issue by jseppanen** [mlflow/mlflow#925] opened 2019-02-26 12:46 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.5
- **MLflow installed from (source or binary)**: pip install mlflow
- **MLflow version (run ``mlflow --version``)**: mlflow, version 0.8.2
- **Python version**: Python 3.6.6 :: Anaconda, Inc.
- **npm version (if running the dev UI):
- **Exact command to reproduce**: `mlflow server --file-store /bigdata/mlflow --host 0.0.0.0`

### Describe the problem
MLflow UI shows Niagara falls with "Oops! Something went wrong" every time I try opening it. I've been using it for two months, but recently it has started crashing until today I cannot get the UI to open at all anymore.

### Logs

server logs after fresh restart:
```
[2019-02-26 12:34:36 +0000] [9] [INFO] Starting gunicorn 19.9.0
[2019-02-26 12:34:36 +0000] [9] [INFO] Listening at: http://0.0.0.0:5000 (9)
[2019-02-26 12:34:36 +0000] [9] [INFO] Using worker: sync
[2019-02-26 12:34:36 +0000] [12] [INFO] Booting worker with pid: 12
[2019-02-26 12:34:36 +0000] [14] [INFO] Booting worker with pid: 14
[2019-02-26 12:34:36 +0000] [15] [INFO] Booting worker with pid: 15
[2019-02-26 12:34:36 +0000] [18] [INFO] Booting worker with pid: 18
[2019-02-26 12:35:30 +0000] [9] [CRITICAL] WORKER TIMEOUT (pid:14)
[2019-02-26 12:35:30 +0000] [14] [INFO] Worker exiting (pid: 14)
[2019-02-26 12:35:30 +0000] [28] [INFO] Booting worker with pid: 28
```

￼browser console logs when opening UI:
```
setupAjaxHeaders.js:22 
{_xsrf: "2|a583f945|b32757069a3ea1c54e37f87dba1c1428|1549020795"}
service-worker.js:1 Uncaught (in promise) Error: Request for http://localhost:5000/static-files/static-files/static/css/main.fbf8a477.css returned a response with status 404
    at service-worker.js:1
service-worker.js:1 Uncaught (in promise) Error: Request for http://localhost:5000/static-files/static-files/static/css/main.fbf8a477.css returned a response with status 404
    at service-worker.js:1
jquery.js:9355 POST http://localhost:5000/ajax-api/2.0/preview/mlflow/runs/search net::ERR_EMPTY_RESPONSE
Actions.js:155 XHR failed 
{readyState: 0, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
react-dom.production.min.js:151 TypeError: Cannot read property 'getErrorCode' of undefined
    at errorRenderFunc (ExperimentPage.js:122)
    at e.value (RequestStateWrapper.js:51)
    at f (react-dom.production.min.js:131)
    at beginWork (react-dom.production.min.js:138)
    at o (react-dom.production.min.js:176)
    at a (react-dom.production.min.js:176)
    at x (react-dom.production.min.js:182)
    at y (react-dom.production.min.js:181)
    at v (react-dom.production.min.js:181)
    at d (react-dom.production.min.js:180)
AppErrorBoundary.js:19 TypeError: Cannot read property 'getErrorCode' of undefined
    at errorRenderFunc (ExperimentPage.js:122)
    at e.value (RequestStateWrapper.js:51)
    at f (react-dom.production.min.js:131)
    at beginWork (react-dom.production.min.js:138)
    at o (react-dom.production.min.js:176)
    at a (react-dom.production.min.js:176)
    at x (react-dom.production.min.js:182)
    at y (react-dom.production.min.js:181)
    at v (react-dom.production.min.js:181)
    at d (react-dom.production.min.js:180)
:5000/#/experiments/1:1 Uncaught (in promise) 
t {xhr: {…}}
﻿```

**Comment by jakubczakon** [comment] 2019-03-28 17:02
@jseppanen 
You could also have your MLflow projects hosted on [neptune.ml][1]. 
It should solve the problems with the UI. An additional benefit is that you can share stuff with others.
For example, let me share [some experiment runs][2] with you. 

I know it sounds sales-y but Neptune is actually free (for non-organizations) and I really feel that this integration brings a lot of value to the MLflow community.

Also if you are interested, I have just written a [blog post about it][3].

  [1]: https://neptune.ml/?utm_source=stack_exchange&utm_medium=forum&utm_campaign=neptune_is_free&utm_term=mlflow
  [2]: https://ui.neptune.ml/jakub-czakon/mlflow-integration/experiments
  [3]: https://medium.com/neptune-ml/collaborate-on-mlflow-experiments-in-neptune-fb4f8f84a995"

**Comment by 5ke** [comment] 2019-06-17 07:35
Same problem here! Started a parameter search before the weekend and have therefore run far more experiments than before. Now I can't start the ui anymore. Where do I start trouble shooting?

**Comment by 5ke** [comment] 2019-06-17 09:15
It turns out that the ui simply doesn't handle too many runs (in my case it starts struggling when mlruns contains more than circa 1000 experiments). Around this threshold the ui becomes unstable (sometimes crashes, sometimes works, but it's never quick&responsive), and eventually there are too many runs and it won't load at all. 

This goes a bit against the philosophy of being able to track _all_ your experiments. 

Would using a local db instead of file storage help? Hosting externally is not an option for me. 

As a side note: during troubleshooting I discovered that when you move runs around into different folders, it's important to update the artifact_location parameter in the main meta.yaml, otherwise you'll experience a different type of crash, without a clear warning.

**Comment by selimonat** [comment] 2019-07-22 18:23
same here. ui either timeouts, or crashes with about 650 runs... sometimes works, mostly doesn't.

**Comment by Zangr** [comment] 2019-07-26 22:31
In Mlflow 1.1 the runs listing has been changed to show the first 100 runs + a "Load more" button if you have more than 100. Could you please try and see if that makes your situation better?

**Comment by selimonat** [comment] 2019-07-27 08:30
We were checking that out few days ago, got exactly the same error.

**Comment by CrankyDragon** [comment] 2019-08-08 16:22
So I just started running into to this issue after upgrading to 1.0.0+ and noticed that the URL for static files is incorrect causing worker to block. Basically if I switch:
http://localhost:5000/static-files/static-files/static/css/main.fbf8a477.css
to:
http://localhost:5000/static-files/static/css/main.fbf8a477.css
These assets load fine. Anyone have a patch for this?

**Comment by datsabk** [comment] 2019-08-28 05:58
Any update on this issue? It still exists on v1.2.0.0

**Comment by Nintorac** [comment] 2020-01-13 03:15
Still getting this issue in MLFlow 1.4. Is the situation improved by using a database backend?

**Comment by HungUnicorn** [comment] 2020-03-24 10:04
getting issue with 1.7 and postgres backend

**Comment by gkonstanty** [comment] 2020-04-29 11:31
It is the same for 1.7 without postgres backend

**Comment by gkonstanty** [comment] 2020-06-23 17:52
I have just upgraded server to run on 1.9.0 version (without postgres backend) and nothing has changed. 

Adding ` --gunicorn-opts "--timeout 180"` has somehow helped, but the number of our experiments is constantly growing, so even 180sec will be not sufficient soon. And waiting so long for some simple queries results is kinda annoying.

Could you please check this issue?

**Comment by faddey-w** [comment] 2020-07-06 13:15
same issue, number of runs is ~50. In my case this machine also runs Tensorboard which uses a lot of RAM - look like less available RAM makes this issue more severe.

**Comment by tw-rwth** [comment] 2020-08-19 02:11
I face the same issue with version 1.10.0 and file system. All files are generated as expected, but the same "WORKIER TIMEOUT" message returns when I try to access individual records (i.e., clicking date's hyperlinks).

**Comment by Zangr** [comment] 2020-08-20 19:52
Reopening this issue as per community request and reassign priority to get it into the queue.

**Comment by spott** [comment] 2020-09-22 16:30
@gkonstanty : where are you adding the `--gunicorn-opts "--timeout 180"` option?

**Comment by 5ke** [comment] 2020-10-01 09:33
> @gkonstanty : where are you adding the `--gunicorn-opts "--timeout 180"` option?

I couldn't get `mlflow ui --gunicorn-opts "--timeout 180"` to work either (error: `no such option --gunicorn-opts`)

But the following worked for me:
`GUNICORN_CMD_ARGS="--timeout 180" mlflow ui`

**Comment by gkonstanty** [comment] 2020-10-01 11:04
Sorry, @spott, I missed your msg.

I'm adding it to `mlflow server`: 
```
mlflow server --host 0.0.0.0 -p 5000 --backend-store-uri /mlflow/data/ --default-artifact-root /mlflow/artifacts/ --gunicorn-opts "--timeout 180"
```

**Comment by kenimou** [comment] 2021-03-15 20:37
I have the same issue (version 1.14.1) and I use Postgres as the backend database. When I access the UI, the list of experiments doesn't load and the spinner just keeps spinning. To me it feels like it could not query the database to display the data.
 
It happens very often (> 50% of the time when I try to access the UI, especially after a run is finished) and I don't even have a lot of experiments (<10 per collection, 2 collections in total).

**Comment by sergeyleyko** [comment] 2021-08-03 08:59
mlflow 1.18, year 2021, issue is still here..

**Comment by daniel-beyond** [comment] 2021-11-22 10:48
mlflow 1.21 same issue...

**Comment by dprateek1991** [comment] 2022-03-01 07:55
I received somewhat better performance with this -

mlflow server --backend-store-uri=postgresql://postgres:${RDS_PASSWORD}@${RDS_HOST}:5432/mlflow --default-artifact-root=${ARTIFACT_STORE} --host 0.0.0.0 --port 5000 --gunicorn-opts "--worker-class gevent --threads 3 --workers 3 --timeout 300  --keep-alive 300 --log-level INFO"

**Comment by jmahlik** [comment] 2022-06-28 13:26
It seems like limiting the initial experiments displayed and having a "load more" button similar to how the runs pages work might help. 

The issue indeed presents only when there are about 1000+ experiments. The python apis continue to function fine with a large number of experiments, it's only the ui/js side that gets bogged down.

I tracked down how loading more runs was implemented
https://github.com/mlflow/mlflow/pull/1564. Maybe some of the implementation could be borrowed?

**Comment by marioGab** [comment] 2022-06-28 17:20
I only have 3 to 5 experiments but still get this error. I just have alot of metrics and parameters in each experiment. So the "load more" idea is not possible.

**Comment by alokpadhi** [comment] 2022-06-28 17:38
Well I found one workaround here. Try `mlflow server -h 0.0.0.0 -p 5000 --backend-store-uri postgresql://DB_USER:DB_PASSWD@DB_ENDPOINT:5432/DB_NAME --default-artifact-root s3://S3_BUCKET_NAME --gunicorn-opts "--timeout 0"`

This will wait till the data transfer finishes and loads, I have to delete a few of my experiments from my S3 bucket to make it load a little faster which I think is not a very welcoming workaround.

Will have to wait for a permanent fix to this.

**Comment by jmahlik** [comment] 2022-07-20 17:19
With a large timeout set, our problem seems to be only with the ui generating the experiments table with 1000+ experiments. I wonder if defaulting the experiments side bar to hidden would help as a short term fix? Collapsing the sidebar seems to fix the problem (after waiting a few minutes for it to load). Yes, it would break almost immediately when someone clicks to expand it, but a user could still use the ui if they knew the experiment id before hand. 

Maybe these are really two separate issues. One for large runs and one for experiments on the home page?

**Comment by sergeyleyko** [comment] 2022-07-21 07:04
The problem is not only with a large number of experiments but with a large number of experiment metrics logged, like in my case.
Thus the issue is due to a bad UI design, and I suppose it can be fixed with big refactoring only.

**Comment by ptavaressilva** [comment] 2022-09-25 08:43
Problem persists on 1.28.0
MLflow is great, but for me this bug renders it practically useless.

**Comment by ChenchengLiang** [comment] 2022-12-16 11:09
Uses http in browser instead of https works for me.

**Comment by crowne** [comment] 2023-06-29 12:23
I was getting this error when clicking on experiments while I had not correctly configured my blob storage.
Once the configuration was corrected then error went away.

**Comment by hvanmegen** [comment] 2023-07-11 11:03
> I was getting this error when clicking on experiments while I had not correctly configured my blob storage. Once the configuration was corrected then error went away.

What did you change to get rid of this error?

**Comment by hvanmegen** [comment] 2023-07-11 11:04
> Uses http in browser instead of https works for me.
oh, seriously?

**Comment by crowne** [comment] 2023-07-11 12:23
> > I was getting this error when clicking on experiments while I had not correctly configured my blob storage. Once the configuration was corrected then error went away.
> 
> What did you change to get rid of this error?

I had to change the format of the environment variable : AZURE_STORAGE_CONNECTION_STRING
The previous incorrect format was preventing the application from connecting to the Azure Blob Storage.

**Comment by alam-shahul** [comment] 2023-08-24 03:56
Is there a way for this issue to get even higher priority? I don't really understand how people use MLflow given that this bug exists. Perhaps it's because most people aren't using the UI feature...

**Comment by pbrit** [comment] 2023-08-29 21:51
I managed to get it fixed by (in my setup):
* increasing the number of workers `--workers 20` (6 should be enough because it's exactly how many connections are allowed per domain in modern browsers, 20 for good measure). 
* switching to `eventlet`

It's worth noting that the root cause, at least in my setup,  has nothing to do with **mlflow** itself. I'm running it in Kubernetes (GKE) and in order to access it on my machine I'm using `kubectl port-forward`.  It looks like the way `kubectl` is proxying the requests exhausts all workers and since they are synchronous by default no new connections can be accepted. Supposedly port-forwarding isn't compatible with the `event` Gunicorn worker class. 

@here Could you describe your setup a bit, please? Are you using `kubectl port-forward` or anything similar to it?

**Closed** 2023-10-02 20:11 UTC
Labels: area/uiux, priority/important-soon

**Comment by simonamtoft** [comment] 2024-09-13 06:57
> I received somewhat better performance with this -
> 
> mlflow server --backend-store-uri=postgresql://postgres:${RDS_PASSWORD}@${RDS_HOST}:5432/mlflow --default-artifact-root=${ARTIFACT_STORE} --host 0.0.0.0 --port 5000 --gunicorn-opts "--worker-class gevent --threads 3 --workers 3 --timeout 300 --keep-alive 300 --log-level INFO"

This seemed to work for me :)

**Comment by viniciusczar** [comment] 2024-12-26 20:11
Whether you don't figure out way to fix that, i did that:
Created my docker image without "--app-name basic-auth" of mlflow command, and input basic auth on my Ingress Nginx as a responsible for that, you can do on Nginx Proxy too.

Dockerfile: 

FROM python:3.9-slim

ENV MLFLOW_HOME /mlflow
ENV MLFLOW_SERVER_HOST 0.0.0.0
ENV MLFLOW_SERVER_PORT 5000
ENV MLFLOW_TRACKING_USERNAME=admin
ENV MLFLOW_TRACKING_PASSWORD=YourPassHere

WORKDIR $MLFLOW_HOME

RUN pip install mlflow psycopg2-binary

#COPY basic_auth.ini /mlflow/basic_auth.ini
#RUN export MLFLOW_AUTH_CONFIG_PATH=/mlflow/basic_auth.ini

EXPOSE $MLFLOW_SERVER_PORT

CMD mlflow server --backend-store-uri $BACKEND_STORE_URI \
    --default-artifact-root $ARTIFACT_ROOT \
    --host 0.0.0.0 \
    --port 5000 \
    --gunicorn-opts "--workers 4 --timeout 0 --log-level INFO" \

**Comment by viniciusczar** [comment] 2025-05-30 14:37
For all of us that have that problem with authenticate: This is my solution works on ubuntu:

docker-compose.yaml
```
version: '3.8'
services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      # ============= AWS S3 CONFIGURATION =============
      - AWS_ACCESS_KEY_ID=YOU_KNOW
      - AWS_SECRET_ACCESS_KEY=YOU_KNOW
      - AWS_DEFAULT_REGION=YOU_KNOW
      
      # ============= MLFLOW DATABASE CONFIGURATION =============
      - BACKEND_STORE_URI=SQL_FIRST_DB_URI_HERE
      - ARTIFACT_ROOT=s3://YOU_KNOW
      - AUTH_DATABASE_URI=SQL_SECOND_DB_URI_HERE
      
      # ============= SECURITY CONFIGURATION =============
      - MLFLOW_FLASK_SERVER_SECRET_KEY=A_GREAT_STRING_HERE_WHAT_YOU_CHOICE
      - MLFLOW_TRACKING_USERNAME=USERNAME_HERE
      - MLFLOW_TRACKING_PASSWORD=PASSWORD_CONSOLE_HERE
 
      # ============= GUNICORN PRODUCTION SETTINGS =============
      # workers: Recomended (2 x cores CPU) + 1
      - MLFLOW_WORKERS=5
      - GUNICORN_TIMEOUT=120
      - GUNICORN_MAX_REQUESTS=1000
      - GUNICORN_MAX_REQUESTS_JITTER=50
      - GUNICORN_PRELOAD=true
      - GUNICORN_WORKER_CLASS=sync
```

Dockerfile:
```
FROM python:3.9-slim

ENV MLFLOW_HOME /mlflow
ENV MLFLOW_SERVER_HOST 0.0.0.0
ENV MLFLOW_SERVER_PORT 5000

WORKDIR $MLFLOW_HOME

# Instalar dependências
RUN pip install mlflow[auth] psycopg2-binary

# Criar diretório para configuração
RUN mkdir -p /etc/mlflow

EXPOSE $MLFLOW_SERVER_PORT

# Script inline para gerar configuração e iniciar MLflow
CMD mkdir -p /etc/mlflow && \
    echo "[mlflow]" > /etc/mlflow/basic_auth.ini && \
    echo "default_permission = READ" >> /etc/mlflow/basic_auth.ini && \
    echo "database_uri = ${AUTH_DATABASE_URI}" >> /etc/mlflow/basic_auth.ini && \
    echo "admin_username = ${MLFLOW_TRACKING_USERNAME}" >> /etc/mlflow/basic_auth.ini && \
    echo "admin_password = ${MLFLOW_TRACKING_PASSWORD}" >> /etc/mlflow/basic_auth.ini && \
    echo "authorization_function = mlflow.server.auth:authenticate_request_basic_auth" >> /etc/mlflow/basic_auth.ini && \
    export MLFLOW_AUTH_CONFIG_PATH=/etc/mlflow/basic_auth.ini && \
    echo "Starting MLFlow server with auth..." && \
    mlflow server \
        --app-name basic-auth \
        --backend-store-uri ${BACKEND_STORE_URI} \
        --serve-artifacts \
        --artifacts-destination ${ARTIFACT_ROOT} \
        --host 0.0.0.0 \
        --port 5000 \
        --workers ${MLFLOW_WORKERS:-4} \
        --gunicorn-opts "--timeout ${GUNICORN_TIMEOUT:-120} $([ \"${GUNICORN_PRELOAD}\" = \"true\" ] && echo \"--preload\") --max-requests ${GUNICORN_MAX_REQUESTS:-1000} --max-requests-jitter ${GUNICORN_MAX_REQUESTS_JITTER:-50} --worker-class ${GUNICORN_WORKER_CLASS:-sync}"
```

**Comment by danielpolimac** [comment] 2025-07-09 09:40
Rebuilding  my Pyenv Python solved the issue for me:

pyenv uninstall 3.12.3
pyenv install 3.12.3
pyenv global 3.12.3

python3 -m venv ~/mlflow-clean
source ~/mlflow-clean/bin/activate
pip install --upgrade pip
pip install mlflow

mlflow ui --host 127.0.0.1 --port 5000
