### ISSUE TITLE
mlflow project can't pickle

### ISSUE THREAD

**Issue by panxuexue** [mlflow/mlflow#162] opened 2018-07-17 13:08 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
when i run my mfflow project ,the python  raise TypeError:"can't pickle %s objects" % base.__name__
TypeError: can't pickle module objects
I don't know how to solve it

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by smurching** [comment] 2018-07-17 20:23
Hi @panxuexue, thanks for reporting this issue - could you post the code you're trying to run & the full Python stacktrace? Thanks!

**Comment by smurching** [comment] 2018-08-11 00:13
@panxuexue this seems like a duplicate of #183 - let me know if I'm wrong, will close this for now but feel free to reopen!

**Closed by smurching** 2018-08-11 00:13 UTC
