### ISSUE TITLE
'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte

### ISSUE THREAD

**Issue by agilebean** [mlflow/mlflow#698] opened 2018-11-08 13:48 UTC
### System information
- **OS Platform and Distribution **: OSX 14.2 (Latest release)
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 0.7.0
- **Python version**:  3.6
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
After successful run, mlflow ui displays `Oops! Something went wrong.` page.
The following error is thrown:
```
'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
```

Complete Stack trace:

```
  File "/Users/agilebean/anaconda3/envs/mlflow/lib/python3.6/codecs.py", line 503, in read    
newchars, decodedbytes = self.decode(data, self.errors) 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3131: invalid start byte
```

**Comment by agilebean** [comment] 2018-11-08 14:17
If it's of any help, I found the file causing the problem. 
Deleting the file directory solved the problem but there is absolutely no hint why there was a codec problem as the logged information is exactly the same as previous runs.
[291516e0411b478aa5d7b4adee327e41.zip](https://github.com/mlflow/mlflow/files/2562074/291516e0411b478aa5d7b4adee327e41.zip)

**Comment by agilebean** [comment] 2018-11-10 04:28
Hi @mani,
no this is the only out of 34 runs that broke.
So I don't understand how to read the error indicating byte xxx and Unicode read error. Where in this uri or else should that happen and how can you find that character??

**Comment by mparkhe** [comment] 2018-11-11 18:18
The content from `meta.yaml` file (excerpt pasted above) did not look right--there is a new line in `artifact_uri` value. That should have affected all the other runs on the experiment, unless this file manually was edited, somehow.

If not, I am not sure how to reproduce this error. Do you possibly have a command sequence that can reproduce this error?

**Comment by dbczumar** [comment] 2019-07-26 21:46
@agilebean I am going to close the issue due. Please feel free to reopen it if the problem persists on MLflow 1.1.

**Closed by dbczumar** 2019-07-26 21:46 UTC

**Comment by lukasmeggle** [comment] 2025-02-03 15:03
The issue was probably caused by OSX creating .DS_Store files in the dirs. They don't show up even when "show hidden files" is activated.
This happens as soon as you access the mlflow dirs from the finder.

According to your ZIP there where files in:
```
291516e0411b478aa5d7b4adee327e41/.DS_Store
291516e0411b478aa5d7b4adee327e41/artifacts/.DS_Store
291516e0411b478aa5d7b4adee327e41/params/.DS_Store
```

I just wrote a small python script to run before launching the mlflow server:
```
import os
current_dir = os.getcwd()
for root, dirs, files in os.walk(current_dir):
    for file in files:
        if file == ".DS_Store":
            file_path = os.path.join(root, file)
            os.remove(file_path)
```

This solves the problem for me.
