### ISSUE TITLE
mlflow ui rerun needs to delete cookies and cache

### ISSUE THREAD

**Issue by DanlanChen** [mlflow/mlflow#948] opened 2019-03-04 21:33 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:mac os
- **MLflow installed from (source or binary)**: library
- **MLflow version (run ``mlflow --version``)**: 0.8.2
- **Python version**: 3.6.8
- **npm version (if running the dev UI):5.6.0
- **Exact command to reproduce**:mlflow ui

### Describe the problem
needs to delete the cache and cookies in web browser to see the result after running `mlflow ui` again. 

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks,
please include the full traceback. Large logs and files should be attached.
Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by jakubczakon** [comment] 2019-03-28 16:59
@DanlanChen 
You could also have your MLflow projects hosted on [neptune.ml][1] knowledge sharing hub. 
There are two benefits to it:

 - you can avoid all the problems with MLflow's UI,
 - you can share your experiment runs with everyone. For example, [check out this project][2]. 

We have recently released a free Neptune version and developed integration with MLflow which, I think, brings a lot of value to the community.

Also if you are interested, I have just written a [blog post about it][3].

  [1]: https://neptune.ml/?utm_source=stack_exchange&utm_medium=forum&utm_campaign=neptune_is_free&utm_term=mlflow
  [2]: https://ui.neptune.ml/jakub-czakon/mlflow-integration/experiments
  [3]: https://medium.com/neptune-ml/collaborate-on-mlflow-experiments-in-neptune-fb4f8f84a995"

**Comment by dbczumar** [comment] 2019-07-26 21:38
@DanlanChen Can you try reproducing this issue on MLflow 1.1? I cannot reproduce this behavior. I am going to close this issue; please feel free to reopen it if the problem persists.

**Closed by dbczumar** 2019-07-26 21:38 UTC
