### ISSUE TITLE
[BUG] Too many scrollbars in experiment view

### ISSUE THREAD

**Issue by 9dogs** [mlflow/mlflow#5129] opened 2021-11-30 12:00 UTC
### Willingness to contribute
The MLflow Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the MLflow code base?

- [ ] Yes. I can contribute a fix for this bug independently.
- [ ] Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.
- [x] No. I cannot contribute a bug fix at this time.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker python:3.10-slim-buster
- **MLflow installed from (source or binary)**: binary, `pip install mlflow`
- **MLflow version (run ``mlflow --version``)**: 1.22.0
- **Python version**: 3.10
- **npm version, if running the dev UI**: -
- **Exact command to reproduce**: -

### Describe the problem
Too many scrollbars - see picture. 

![image (2)](https://user-images.githubusercontent.com/432235/144043532-4ba68106-13b0-46f7-8b16-0eab612864b8.png)

I believe this line to blame: https://github.com/mlflow/mlflow/blob/d79a81671f50bf2b4d3105160912fbbee742cdec/mlflow/server/js/src/experiment-tracking/components/ExperimentView.css#L332

### What component(s), interfaces, languages, and integrations does this bug affect?
Components 
- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

Interface 
- [x] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

Language 
- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

Integrations
- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by SeguinBe** [comment] 2021-12-07 23:10
I'm no react developper but my guess on the cause would be more on the fact that there are three `overflow-y: scroll;` in [ExperimentListView.css](https://github.com/mlflow/mlflow/blob/d79a81671f50bf2b4d3105160912fbbee742cdec/mlflow/server/js/src/experiment-tracking/components/ExperimentListView.css)

**Comment by harupy** [comment] 2022-06-06 05:14
Fixed by #5159.

**Closed by harupy** 2022-06-06 05:14 UTC
Labels: bug, area/uiux
