### ISSUE TITLE
Local installation mlflow project error

### ISSUE THREAD

**Issue by 15021687693** [mlflow/mlflow#156] opened 2018-07-16 07:31 UTC
### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **MLflow installed from (source or binary)**: 
- **MLflow version (run ``mlflow --version``)**:
- **Python version**: 2.7.13
- **npm version (if running the dev UI):
- **Exact command to reproduce**:

### Describe the problem
[root@datanode03 mlflow-master]# python setup.py install

### Source code / logs
Installed /usr/local/lib/python2.7/site-packages/mlflow-0.2.1-py2.7.egg
Processing dependencies for mlflow==0.2.1
Searching for querystring_parser
Reading https://pypi.python.org/simple/querystring_parser/
Download error on https://pypi.python.org/simple/querystring_parser/: [SSL: CE
RTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!Reading https://pypi.python.org/simple/querystring-parser/
Download error on https://pypi.python.org/simple/querystring-parser/: [SSL: CE
RTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!Couldn't find index page for 'querystring_parser' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FA
ILED] certificate verify failed (_ssl.c:661) -- Some packages may not be found!No local packages or download links found for querystring_parser
error: Could not find suitable distribution for Requirement.parse('querystring
_parser')

**Comment by smurching** [comment] 2018-07-16 18:41
Hi @15021687693, thanks for reporting this issue - I can't seem to reproduce locally. Could I ask what pip version you're using? Looking at the output of your installation, I can access the URLs that get printed (e.g. https://pypi.python.org/simple/querystring_parser/). I suspect the certificate verification failures are what's ultimately preventing the installation - are you able to `pip install` other packages hosted on PyPi? If the problem is certificate verification, the fixes suggested [here](https://stackoverflow.com/a/29751768) might work.

**Comment by 15021687693** [comment] 2018-07-17 02:01
**# pip install querystring_parser**
Collecting querystring_parser
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, s
tatus=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/querystring-parser/  Retrying (Retry(total=3, connect=None, read=None, redirect=None, s
tatus=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/querystring-parser/  Retrying (Retry(total=2, connect=None, read=None, redirect=None, s
tatus=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/querystring-parser/  Retrying (Retry(total=1, connect=None, read=None, redirect=None, s
tatus=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/querystring-parser/  Retrying (Retry(total=0, connect=None, read=None, redirect=None, s
tatus=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)': /simple/querystring-parser/  Could not fetch URL https://pypi.org/simple/querystring-parser/: T
here was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/querystring-parser/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)) - skipping  Could not find a version that satisfies the requirement querystrin
g_parser (from versions: )No matching distribution found for querystring_parser
Could not fetch URL https://pypi.org/simple/pip/: There was a proble
m confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),)) - skipping

**Comment by max-allen-db** [comment] 2019-07-26 21:15
Hey @15021687693,

I'm going to close this issue as it's been a while and I believe pip, pypi, and the MLflow install process is more stable now. See the README and the Contributing guide for up-to-date instruction on how to install MLflow 1.1.0

**Closed by max-allen-db** 2019-07-26 21:15 UTC
