### ISSUE TITLE
[FR] I can compare runs of different experiments. Can you generalize it ?

### ISSUE THREAD

**Issue by jdlesage** [mlflow/mlflow#2112] opened 2019-11-18 16:06 UTC
## Describe the proposal & Motivation
Currently we put all runs in the same experiment, just to be able to compare them. It makes our experiments totally messy. 
I would like create more experiments with less runs in order to have a better organization in my server. But I want to be able to compare them.
We love tags. That would be great to compare all runs with a given tag cross experiments.

### Proposed Changes
Probably nothing... Today if I call `<my_mlflow_server_url>/#/compare-runs?runs=[...]` with runs from different experiments ... it works! 
I am wondering why there is a constraint on the experiment id. Is it possible to remove it ? It will enable to create runs views between different experiments. For example, a view that lists all the runs launched by a user. (For example, what are my 20 latest runs ?)

**Comment by Christoph460** [comment] 2020-01-17 08:55
@jdlesage Is this url call still working for you?
`mlflow, version 1.5.0`

`http://localhost:5000/#/compare-runs?runs=["run1","run2"]`

In my case its not working without providing `&experiment=0` at the URL end.

**Comment by florianblume** [comment] 2020-03-12 15:04
Would it be an option to have a static _All_ experiment at the top of the list of the experiments which simply loads all experiments? It could show a slightly different table which has an additional column called _Experiment_. This would allow to compare only some experiments.

**Comment by mohammedayub44** [comment] 2021-04-13 17:12
Any update on this ? 
I have been bombarding my one experiment with many runs for the same reason. 

Thanks !

**Comment by JarnoRFB** [comment] 2022-02-17 10:19
Sound like a duplicate of #1414.

**Comment by dbczumar** [comment] 2022-12-06 05:00
This has been addressed in https://github.com/mlflow/mlflow/pull/5971. Thank you for using MLflow!

**Closed by dbczumar** 2022-12-06 05:00 UTC
Labels: enhancement, area/uiux, area/tracking, priority/backlog, needs design
