### ISSUE TITLE
[BUG]load_model not found error

### ISSUE THREAD

**Issue by xinglong700000** [mlflow/mlflow#7645] opened 2023-01-05 00:43 UTC
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

- Client: 2.0.1
- Tracking server: 1.23.1

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Enterprise 21H2
- **Python version **: 3.10
- **yarn version, if running the dev UI**:

### Describe the problem

I have registered a model to mlflow model registry.

When I call ‘load_model’ function to try to fetch the model from model registry and try to make prediction, mlflow cannot find the model from the model name and version number I provided:

```
model_name = "sample-ann-1"
version = 1
loaded_model = mlflow.pyfunc.load_model("models:/{}/{}".format(model_name, version))
```

And return the following error:

`"mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from s3://{bucket}/5/8429aef5d8304990ae035c638db093e7/artifacts/../saved-model/model20/: {'': "ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')"}"`

However, if I provide the artifact path(s3://{bucket}/5/8429aef5d8304990ae035c638db093e7/artifacts/../saved-model/model20/) to "load_model" API, it will find and fetch the model

When I open s3 browser to check the file in artifact path (s3://{bucket}/5/8429aef5d8304990ae035c638db093e7/artifacts/../saved-model/model20/), I found the model is in the path, not sure why mlflow return 404 not found error if I only provide model name and version.
<img width="391" alt="image" src="https://user-images.githubusercontent.com/121919572/210675525-6ad3fd63-df50-4a7c-a3cf-087e3601bc36.png">

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

import mlflow

tracking_url = "{tracking url}"
mlflow.set_tracking_uri(tracking_url)

mlflow.set_experiment('test_mlflow')
loaded_model = mlflow.pyfunc.load_model("models:/sample-ann-1/1")

### Stack trace

```
Traceback (most recent call last):
  File "C:\PycharmProjects\ml-flow-project-example2\model\load-registered-model.py", line 23, in <module>
    loaded_model = mlflow.pyfunc.load_model("models:/{}/{}".format(model_name, version))
  File "C:\PycharmProjects\ml-flow-project-example2\venv\lib\site-packages\mlflow\pyfunc\__init__.py", line 509, in load_model
    local_path = _download_artifact_from_uri(artifact_uri=model_uri, output_path=dst_path)
  File "C:\PycharmProjects\ml-flow-project-example2\venv\lib\site-packages\mlflow\tracking\artifact_utils.py", line 100, in _download_artifact_from_uri
    return get_artifact_repository(artifact_uri=root_uri).download_artifacts(
  File "C:\PycharmProjects\ml-flow-project-example2\venv\lib\site-packages\mlflow\store\artifact\models_artifact_repo.py", line 126, in download_artifacts
    return self.repo.download_artifacts(artifact_path, dst_path)
  File "C:\PycharmProjects\ml-flow-project-example2\venv\lib\site-packages\mlflow\store\artifact\artifact_repo.py", line 263, in download_artifacts
    raise MlflowException(
mlflow.exceptions.MlflowException: The following failures occurred while downloading one or more artifacts from s3://{bucket}/5/8429aef5d8304990ae035c638db093e7/artifacts/../saved-model/model20/: {'': "ClientError('An error occurred (404) when calling the HeadObject operation: Not Found')"}
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [X] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [X] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment] 2023-01-06 07:10
@xinglong700000 The `..` in `s3://{bucket}/5/8429aef5d8304990ae035c638db093e7/artifacts/../saved-model/model20/` looks strange to me. How did you log this model?

**Comment by xinglong700000** [comment] 2023-01-06 20:19
> @xinglong700000 The `..` in `s3://{bucket}/5/8429aef5d8304990ae035c638db093e7/artifacts/../saved-model/model20/` looks strange to me. How did you log this model?

I'm not sure, but it is part of the path in s3 registry. If I call loaded_model = mlflow.pyfunc.load_model( `s3://{bucket}/5/8429aef5d8304990ae035c638db093e7/artifacts/../saved-model/model20/`), which the artifact path I input is exactly same as the one in trace back message, mlflow api will be able to fetch the model. Not sure why if I only input model name and version, it won't find it.

By the way, the tracking server version is 1.23.1, but my mlflow client is 2.0.1. Would it cause any problem?

**Comment by harupy** [comment] 2023-01-09 23:51
> mlflow api will be able to fetch the model

Can you elaborate on this?

**Comment by xinglong700000** [comment] 2023-01-10 00:24
> > mlflow api will be able to fetch the model
> 
> Can you elaborate on this?

I logged model by calling following code"
```
run_name = "sample-ann-run5"
with mlflow.start_run(run_name=run_name):
    mlflow.log_param("batch_size", batch_size)
    mlflow.log_param("learning_rate", learning_rate)
    mlflow.log_param("epochs", epochs)

    mlflow.log_metric("train_loss", train_score)
    mlflow.log_metric("train_accuracy", train_acc)
    mlflow.log_metric("loss", test_score)
    mlflow.log_metric("accuracy", test_acc)

    print("start logging model with run: {}".format(run_name))
    mlflow.tensorflow.log_model(model=classifier, registered_model_name="sample-ann-2", artifact_path=model_save_path)
```

When I try to fetch model from model registry, I need to call load_model api with artifact path as parameter:
```
artifact_path = "s3://{bucket}/5/{run_id}/artifacts/../saved-model/model20/"
loaded_model = mlflow.pyfunc.load_model(artifact_path)
```

however, if I call load_model with model name and version number only, it will has the error
`loaded_model = mlflow.pyfunc.load_model("models:/{}/{}".format(model_name, version))`

**Comment by ikrizanic** [comment] 2023-01-14 19:07
> By the way, the tracking server version is 1.23.1, but my mlflow client is 2.0.1. Would it cause any problem?

@xinglong700000 Have you resolved this problem? This version mismatch is most likely the cause for the error you are experiencing.

**Comment by xinglong700000** [comment] 2023-01-17 22:29
> 

I emailed the person who's in charge of Mlflow server in my workplace, he said he will update the mlflow version on server. Let me ask him again.

**Comment by xinglong700000** [comment] 2023-01-17 22:29
> > By the way, the tracking server version is 1.23.1, but my mlflow client is 2.0.1. Would it cause any problem?
> 
> @xinglong700000 Have you resolved this problem? This version mismatch is most likely the cause for the error you are experiencing.

I emailed the person who's in charge of Mlflow server in my workplace, he said he will update the mlflow version on server. Let me ask him again.

**Comment by BenWilson2** [comment] 2023-01-27 00:27
@labradovy thank you for bringing this up. We're looking into it :)

**Comment by xinglong700000** [comment] 2023-01-27 01:24
> > By the way, the tracking server version is 1.23.1, but my mlflow client is 2.0.1. Would it cause any problem?
> 
> @xinglong700000 Have you resolved this problem? This version mismatch is most likely the cause for the error you are experiencing.

I just found that some of the registered model has no such error. Means I can load them with their model name and version only. However, if I try to load the old registered models, it still has 404 not found error. I think maybe the artifact paths has some mismatch.

**Comment by bali0019** [comment] 2023-01-27 02:52
@labradovy We [merged a fix](https://github.com/mlflow/mlflow/pull/7670) for a related issue to master. Can you please retry using the `master` branch? When you do that, please ensure you set `--default-artifact-root` to a `file://` URI, for example: doing it this way `file:///server_name_a/Mlruns/DEV`, that will just force the path to contain netloc (servername here) to work with `pathlib`, I just don't see that logic handling in the related mlflow code to parse netloc as servername for UNC path. We may have to put a fix on this based on your run against the master branch. If you can report back on whether that works, that will be great. Based on your feedback, we can open an issue to address this if it still persists in the master branch. 
Also, just curious, what is your operation that triggers that exception? It seems like you are either logging or downloading artifacts. 

@xinglong700000 Can you kindly elaborate more on it? perhaps some pseudo code/steps would be great.

**Comment by labradovy** [comment] 2023-01-27 15:32
Thanks for the quick reply.
I just ran the code with the nightly build `mlflow_skinny-2.1.2.dev0-0.fdeb6e27a2e3449d-py3-none-any.whl` and added the file:// to the URI as well. It didn't work.

The operation that triggers the exception is:
```
model = mlflow.pyfunc.load_model(
    f"models:/{tags.model_name}/{tags.model_stage}"
)
```

Like you said I don't see the code handling a separate netloc, I see netloc populated but discarted.

**Comment by bali0019** [comment] 2023-01-27 16:13
@labradovy thank you for getting back to me. I am looking into this and will update you soon (most likely, going to be a PR fix for this).

**Comment by labradovy** [comment] 2023-01-31 15:07
@bali0019 I saw the PR merged and I tried this nightly build `mlflow-2.1.2.dev0-0.b4a14ffce67fdaca-py3-none-any.whl`

It looks like is **working correctly** now, thank you for the support.

When do you think 2.1.2 will be released?

**Comment by BenWilson2** [comment] 2023-01-31 15:31
Issue verified fixed! Thanks to both @xinglong700000 and @labradovy for reporting this issue and @bali0019 for the great set of PRs that fixed it! :D 

@labradovy we aim for approximately monthly releases (give or take a few weeks) and we're gearing up for another release soon. No firm exact date as of yet, but it's coming soon!

**Closed by BenWilson2** 2023-01-31 15:31 UTC
Labels: bug, area/model-registry, language/new

**Comment by labradovy** [comment] 2023-02-21 15:15
> Issue verified fixed! Thanks to both @xinglong700000 and @labradovy for reporting this issue and @bali0019 for the great set of PRs that fixed it! :D
> 
> @labradovy we aim for approximately monthly releases (give or take a few weeks) and we're gearing up for another release soon. No firm exact date as of yet, but it's coming soon!

Hi, just wanted to ask about the new release, it's been 2 months since the last one. Do you guys have an approximate for 2.1.2?

**Comment by BenWilson2** [comment] 2023-02-21 15:31
@labradovy it's coming in the next 2 weeks.
