### ISSUE TITLE
[FR] Change the experiment for a run

### ISSUE THREAD

**Issue by bilelsgh** [mlflow/mlflow#12886] opened 2024-08-05 15:36 UTC
### Willingness to contribute

Yes. I can contribute this feature independently.

### Proposal Summary

Changing the 'experiment_name' of a 'run' could be useful to reorganize our different folders.
It would also prevent us from running again a whole experiment just because we forgot to change the experiment name.a whole experiment again

### Motivation

> #### What is the use case for this feature?
Organize our different experiments after running them

> #### Why is this use case valuable to support for MLflow users in general?
More flexible interface

> #### Why is this use case valuable to support for your project(s) or organization?
I often need to change the experiment name of a run to merge some of them 

> #### Why is it currently difficult to achieve this use case?
Because I found none option to do it

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by daniellok-db** [comment] 2024-08-06 08:40
Seems to be a duplicate of #7444—we understand that this is a pain point, but adding a dedicated API for it would be difficult for reasons [described in this comment](https://github.com/mlflow/mlflow/pull/7445#issuecomment-1338701418).

**Comment by daniellok-db** [comment] 2024-08-08 01:42
closing as duplicate

**Closed by daniellok-db** 2024-08-08 01:42 UTC
Labels: enhancement
