### ISSUE TITLE
[BUG] Global tracer provider will be reset since 2.13.1

### ISSUE THREAD

**Issue by zhengfeiwang** [mlflow/mlflow#12341] opened 2024-06-13 03:34 UTC
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

- Client: 2.13.1
- Tracking server: 1.x.y (I think it does not matter)

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: any
- **Python version**: any
- **yarn version, if running the dev UI**: not applicable

### Describe the problem

#12137 introduces an operation that will force reset the global tracer provider: `reset_tracer_setup()`. Currently I'm not very sure when mlflow will call this function, but this operation will remove all registered exporter, which is not good for me and shall break the Open Telemetry spec.

### Tracking information

```shell
REPLACE_ME
```

### Code to reproduce issue

```
REPLACE_ME
```

### Stack trace

```python
from mlflow.tracing.provider import reset_tracer_setup
from opentelemetry import trace
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import BatchSpanProcessor, SpanExporter, SpanExportResult
from promptflow.tracing import trace as pf_trace


class StdoutSpanExporter(SpanExporter):
    def export(self, spans):
        for span in spans:
            print("trace id:", span.context.trace_id)
            print("span id:", span.context.span_id)
        return SpanExportResult.SUCCESS

    def shutdown(self):
        pass


@pf_trace
def do_something():
    print("Doing something")


def setup_exporter():
    trace.set_tracer_provider(TracerProvider())
    tracer_provider: TracerProvider = trace.get_tracer_provider()
    stdout_span_exporter = StdoutSpanExporter()
    tracer_provider.add_span_processor(BatchSpanProcessor(stdout_span_exporter))


def main():
    setup_exporter()
    reset_tracer_setup()  # this line will force reset tracer provider to NoOpTracerProvider
    do_something()


if __name__ == "__main__":
    main()
```

### Other info / logs

```
REPLACE_ME
```

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [X] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by zhengfeiwang** [comment] 2024-06-13 03:35
btw, seems we need a new component for issue template for tracing related issue.

**Comment by B-Step62** [comment] 2024-06-13 05:48
@zhengfeiwang Thank you for reporting this. The `reset_tracer_setup` method should only be used internally and only called for two cases
1. `mlflow.tracing.disable()` is called.
2. Tracking URI is changed via `mlflow.set_tracking_uri()`.

What is expected behavior for your use case?

**Comment by B-Step62** [comment] 2024-06-13 09:21
@zhengfeiwang Thanks for the clarification! I think that's fair to only disable MLflow related components only i.e. span processor and exporter. Implementation-wise, it should be possible by iterating processors registered in the [_active_span_processor](https://github.com/open-telemetry/opentelemetry-python/blob/ba22b165471bde2037620f2c850ab648a849fbc0/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L1185) field and remove MLflow related instance once, then add a new one via [add_span_processor()](https://github.com/open-telemetry/opentelemetry-python/blob/ba22b165471bde2037620f2c850ab648a849fbc0/opentelemetry-sdk/src/opentelemetry/sdk/trace/__init__.py#L1264C14-L1264C36). It requires a bit hacky access to private fields, but should be straight-forward.

But before jumping into implementation, I would like to clarify the requirements a bit more for this integration:
1. When a custom exporter is configured in addition to MLflow's one, do you expect the MLflow spans are also exported there? I'm asking this because the other way is no - MLflow shouldn't export OTel span that is generated outside its APIs.
2. What about the reversed case? If MLflow starts first and initialize the tracer provider, then `setup_exporter` function call will be ignored as OTel only allow setting tracer provider once. Is this acceptable?

I feel there are no straight-forward answers to these questions, but rather we need a good design considerations with actual integration use case. Would you mind connecting us with promptflow developers to discuss about these points?

**Comment by zhengfeiwang** [comment] 2024-06-13 09:54
@B-Step62 Thanks for the quick response, and I agree to clarify the requirements first, your questions/concerns are valid to discuss, I neither have a good answer to them yet. I will raise these inside prompt flow first, it may take some time for some reasons, but I will get back to you once we have some updates/conclusions. Thank you again!

**Comment by B-Step62** [comment] 2024-06-26 05:52
Hi @zhengfeiwang, I hope you are doing well. We actually made change to the global tracer provider handling. With this fix ^, the existing tracer provider configurations won't be mutated by MLflow.

I close this issue for now, given the original concern should be resolved. However, it doesn't address complex case, for example, both MLflow and PromptFlow spans are created simultaneously. Once you get response from PromptFlow team about any additional requirements, please feel free to open a new issue and tag me. Thank you so much!

**Closed by B-Step62** 2024-06-26 05:52 UTC
Labels: bug, integrations/azure
