### ISSUE TITLE
[FR] A run can store artifacts in the "user" HDFS folder instead of the experiment one.

### ISSUE THREAD

**Issue by jdlesage** [mlflow/mlflow#2082] opened 2019-11-12 13:53 UTC
## Describe the proposal

When I create a run, I would like to override the experiment default artifact uri. I would like also to store my artifacts into my own folder in HDFS. It will enable me to contribute to an experiment owned by someone else.

### Motivation

We use HDFS to store artifacts. If I create an experiment that uses my HDFS folder as default artifact URI. My colleagues cannot create a new runs in my experiment.
Our current workaround is to use "groups" and gives access to the group to the mlflow artifacts folder. All members of the group will be allowed to add artifacts.
 We would like to remove this workaround and enable in MLFlow to have in the same experiment, several runs that use different artifacts folders.

### Proposed Changes
To implement this story, I propose the following changes:
* Override the default artifact URI when I create a run. => add an new option `artifact_uri` to create_run function
* Add a function in HDFS store class to change the default artifact URI to point to a folder in my HDFS folder. For this task, we can assume HDFS folder are like `/user/USERNAME/`
* If I create a run to an experiment with default URI is like `hdfs://namenode/user/some_username/...` replace some_username by my username and store my artifacts in this folder.

**Comment by mparkhe** [comment] 2019-11-13 02:18
The use case is a bit unclear to me. Can you please elaborate on that?

By design experiments are meant to be a collection of runs that several folks on the team can collaborate on. As such, people use experiment as a means to store runs that a team has access to and by extension the run's artifacts, metrics, params, ... etc. As such headless or group-ACLed HDFS accounts make sense.

On the flip side -- as you mentioned, if you want to store artifacts that only you have access to, creating individual experiments backed by individual's HDFS (... etc) folder makes sense.

**Comment by jdlesage** [comment] 2019-11-13 09:11
To clarify my usecase, here two examples:
* Someone in the team starts an experiments but forget to use the headless account. It needs ACL manipulation to enable the other members of his team to contribute to his experiments. And, one may argue it is not a good practice to allow other people to write to the user personal folder.
* There are often people that don't belong to the team that want to contribute to an experiment. For example, we encourage sort of 'kaggle challenges' internally. In this case, there are no common groups between the team and the contributor.

So my suggestion is to allow users to store artifacts in their own hdfs folder.

By the way, what do you think about overriding the artifacts uri at run creation (ie add an argument in https://mlflow.org/docs/latest/rest-api.html#create-run) ? The uri set in experiment will become a default uri. As far I understand, in the data model, each run has already its own artifact uri. This change seems a no-brainer and will be very useful.

**Comment by mparkhe** [comment] 2019-11-15 07:49
`artifact_uri` field in `RunInfo` was a response field to point to the artifact location for the run and was not designed as a means to set a new artifact location when creating new runs. Your proposal changes the data model and would need some thinking if it affects different clients and backends and backend store implementations. This is complicated since MLflow supports plugins and developers and users of MLflow APIs could have their custom backends using abstract class interfaces. You can follow [`#mlflow-plugins` slack channel](https://join.slack.com/t/mlflow-users/shared_invite/enQtMzkxMTAwNTcyODM5LTkzMDFhNzliNjExOGQ1ZGI1ZmFlMGE5YWE1OTI4ZGM1ZWZmYzc3NGNiZTM3YjgwOTdlODAzMjJhZTdiN2Y3MWY)

Another issue is that a single experiment was designed to be a collection of runs that is accessible to anyone who has access to the experiment data. Having different runs with different view access might break some of the UI components for compare etc. If you want different groups of users accessing subsets of runs, you really want to create different experiments.

**Comment by jdlesage** [comment] 2019-11-18 15:44
Maybe there is a misunderstanding, I don't see in which case we cannot compare experiments due to wrong artifacts rights.
Currently as far I know, we can only compare metrics, params that are stored in file store or SQL (not in artifacts). The compare runs view do not read artifacts.

Then, the `log_artifact` method and `download_artifacts` methods in `tracking/client.py` only rely on the `run.info.artifact_uri` then generates the artifact repository client. And that's nice! If plugins rely on this official client, I think this FR will not break them.

**Comment by chenmoneygithub** [comment] 2023-10-10 02:21
This issue hasn't received any activity since marked with `awaiting-more-evidence`, so I am closing it. we can reopen on demand.

**Closed by chenmoneygithub** 2023-10-10 02:21 UTC
Labels: enhancement, area/artifacts, area/tracking, priority/awaiting-more-evidence
