### ISSUE TITLE
[BUG] If a git tree has no master branch, but it does have a main branch 'mlflow run' fails

### ISSUE THREAD

**Issue by jagane-infinstor** [mlflow/mlflow#5871] opened 2022-05-14 19:04 UTC
### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### System information

- No custom code. MLflow stack example 'docker'
- Ubuntu 20.04
- pip installed
- mlflow, version 1.25.1
- Python 3.9.7
- **npm version: N/A

### Describe the problem

If I create a public repository on github, it appears to have only the branches origin/HEAD and origin/main. There does not appear to be a branch called master. This causes 'mlflow run <git_url>' to fail because we are looking for a branch called master.
Steps to reproduce:
1. Create a github public repo  using the github web UI (check the 'create README.md box) e.g. https://github.com/jagane-infinstor/mlflow-example-docker.git
2. Copy all the files from mlflow/examples/docker into this repo and push it
3. Now, if I run 'mlflow run https://github.com/jagane-infinstor/mlflow-example-docker.git  -Palpha=0.6' it fails with:
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/utils.py", line 130, in fetch_and_validate_project
    work_dir = _fetch_project(uri=uri, version=version)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/utils.py", line 164, in _fetch_project
    _fetch_git_repo(parsed_uri, version, dst_dir)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/utils.py", line 203, in _fetch_git_repo
    repo.create_head("master", origin.refs.master)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/git/util.py", line 1001, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin/master'

To fix this, we need to check for a branch called main if the check for master fails.

### Code to reproduce issue

mlflow run https://github.com/jagane-infinstor/mlflow-example-docker.git -Palpha=0.6

### Other info / logs

(base) jagane@jaganeworkstation:~$ mlflow run https://github.com/jagane-infinstor/mlflow-example-docker.git
2022/05/14 12:00:08 INFO mlflow.projects.utils: === Fetching project from https://github.com/jagane-infinstor/mlflow-example-docker.git into /tmp/tmpzamejbl5 ===
Traceback (most recent call last):
  File "/home/jagane/anaconda3/bin/mlflow", line 8, in <module>
    sys.exit(cli())
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/cli.py", line 178, in run
    projects.run(
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/__init__.py", line 329, in run
    submitted_run_obj = _run(
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/__init__.py", line 95, in _run
    submitted_run = backend.run(
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/backend/local.py", line 46, in run
    work_dir = fetch_and_validate_project(project_uri, version, entry_point, params)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/utils.py", line 130, in fetch_and_validate_project
    work_dir = _fetch_project(uri=uri, version=version)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/utils.py", line 164, in _fetch_project
    _fetch_git_repo(parsed_uri, version, dst_dir)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/mlflow/projects/utils.py", line 203, in _fetch_git_repo
    repo.create_head("master", origin.refs.master)
  File "/home/jagane/anaconda3/lib/python3.9/site-packages/git/util.py", line 1001, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'origin/master'

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by harupy** [comment] 2022-05-15 03:35
Duplicate of #5718

**Closed** 2022-05-15 14:15 UTC
Labels: bug, area/projects
