### ISSUE TITLE
`schema.json` may not be needed for MLeap flavor

### ISSUE THREAD

**Issue by kevinykuo** [mlflow/mlflow#1278] opened 2019-05-15 22:18 UTC
Currently saving the mleap model flavor involves writing a `schema.json` file https://github.com/mlflow/mlflow/blob/4d1469e6e45db8c7e0a572c5c63e397cb56cc82b/mlflow/mleap.py#L159-L162
This is then used from Java during scoring
https://github.com/mlflow/mlflow/blob/1e0c2bdda70d195c0eb5aa4e3c76e2d51ae98361/mlflow/java/scoring/src/main/java/org/mlflow/sagemaker/PandasSplitOrientedDataFrame.java#L86-L105
However, since this schema is extracted from the input data frame, it can contain more columns than is needed. For example, the example at 
https://github.com/mlflow/mlflow/blob/4d1469e6e45db8c7e0a572c5c63e397cb56cc82b/mlflow/mleap.py#L41-L73
writes the following `schema.json`:
```
{
    "fields": [
        {
            "name": "id",
            "type": "long"
        },
        {
            "name": "text",
            "type": "string"
        }
    ]
}
```
But `"id"` in this case is superfluous.

We can consider getting rid of the `schema.json` file and instead extract the schema from the loaded transformer object
https://github.com/combust/mleap/blob/d276c1c800277a1edcf30dda6e8559c7413b21f8/mleap-runtime/src/main/scala/ml/combust/mleap/runtime/frame/Transformer.scala#L43-L49

cc @dbczumar

**Comment by kevinykuo** [comment] 2019-05-25 05:55
@ancasarb I noticed in https://github.com/mlflow/mlflow/pull/1316 we now derive the schema from the bundle and am curious why we still need the `schema.json` file?

**Comment by ancasarb** [comment] 2019-05-27 11:08
@kevinykuo @dbczumar I've created https://github.com/mlflow/mlflow/pull/1339 to require only the fields needed at scoring time.

I also thought that we could remove the schema.json, but I added an example model, the "regression_model", to the PR where that strategy wouldn't work.

The schema from the transformer is:
```
root
 |-- income: scalar(base=string,nullable=true)
 |-- age: scalar(base=**double**,nullable=true)
 |-- hours_per_week: scalar(base=**double**,nullable=true)
```

and this is the schema that is stored from training time:

```
root
 |-- age: scalar(base=**int**,nullable=true)
 |-- workclass: scalar(base=string,nullable=true)
 |-- fnlwgt: scalar(base=int,nullable=true)
 |-- education: scalar(base=string,nullable=true)
 |-- marital_status: scalar(base=string,nullable=true)
 |-- capital_gain: scalar(base=int,nullable=true)
 |-- hours_per_week: scalar(base=**int**,nullable=true)
 |-- income: scalar(base=string,nullable=true)
```

If we, with the changes in PR #1339, we create the following schema
```
root
 |-- age: scalar(base=**int**,nullable=true)
 |-- hours_per_week: scalar(base=**int**,nullable=true)
 |-- income: scalar(base=string,nullable=true)
```

then MLeap has good casting support (https://github.com/combust/mleap/blob/master/mleap-core/src/main/scala/ml/combust/mleap/core/types/Casting.scala) so it'll be able to convert the ints to doubles, as required. 

When reading this input

```
{
    "data": [
        [
            17,
            25,
            "<=50K"
        ]
    ],
    "columns": [
        "age",
        "hours_per_week",
        "income"
    ]
}```
the PandasSplitOrientedDataFrame reads "age" and "hours_per_week" columns as Integer(s) and creating the leapframe with those as integers and with them typed as doubles in the schema gives an error. But if they're typed as Integer(s) in the input leap frame, even though they're required to be doubles by the model, MLeap is able to do this casting automatically.

I suspect usually the fields will have the same types between training and scoring, so I think PR #1278 would work. Let me know what you think!

**Comment by ancasarb** [comment] 2019-05-27 11:24
I was thinking of maybe renaming schema.json to training_schema.json to make the difference clearer, but that'd be a breaking change.

**Comment by dbczumar** [comment] 2019-05-31 05:44
@ancasarb Can you clarify a couple of things?:

> The schema from the transformer is:
> 
> ```
> root
>  |-- income: scalar(base=string,nullable=true)
>  |-- age: scalar(base=**double**,nullable=true)
>  |-- hours_per_week: scalar(base=**double**,nullable=true)
> ```
> 
> and this is the schema that is stored from training time:
> 
> ```
> root
>  |-- age: scalar(base=**int**,nullable=true)
>  |-- workclass: scalar(base=string,nullable=true)
>  |-- fnlwgt: scalar(base=int,nullable=true)
>  |-- education: scalar(base=string,nullable=true)
>  |-- marital_status: scalar(base=string,nullable=true)
>  |-- capital_gain: scalar(base=int,nullable=true)
>  |-- hours_per_week: scalar(base=**int**,nullable=true)
>  |-- income: scalar(base=string,nullable=true)
> ```

What do we mean by "the schema of the transformer" and "the schema stored at training time"? Is the "schema stored at training time" a synonym for "input schema"?

Additionally, why do these schemas differ?

**Comment by ancasarb** [comment] 2019-06-05 19:07
@dbczumar yes, schema stored at training time is the input schema (but this will contain some fields that are not required for scoring).

mleap adds input/output schema for the Spark transformers and for most transformers this is straightforward to do. There's a couple, like StringIndexer or VectorAssembler, that are a bit more tricky. For e.g., StringIndexer works on any type input, so what mleap does it declares the input schema for it to be a string and handles the casting automatically (if the two types are compatible) to a string if let's say it's given an input of type integer. 

When we get the schema from the bundle/zip, for the string indexer, it'll say that it needs a string, so if we use this schema, we'll need to pass in an actual string, which may or may not be what we had during training. So we lose the automatic casting done by mleap, which now has to be done by the clients who call the predict function.

To see this, see the slight difference between the sample_input.json for the added regression model because the VectorAssembler has the input schema defined as a series of double types of vectors (of doubles). https://github.com/mlflow/mlflow/pull/1405/files#diff-03028ed5534a8a5a115224d2108f20ad vs https://github.com/mlflow/mlflow/pull/1339/files#diff-03028ed5534a8a5a115224d2108f20ad. 

I've raised two options to fix this issue:
- Option 1: https://github.com/mlflow/mlflow/pull/1339
- Option 2: https://github.com/mlflow/mlflow/pull/1405

You can have a look to see which one you prefer - I think that if the schema at scoring time is likely to be the same as at training time, then Option 1 would be preferable.

**Comment by kevinykuo** [comment] 2019-06-07 11:58
Thank you @ancasarb for the explanation! I'm casting a strong vote for Option 2 (https://github.com/mlflow/mlflow/pull/1405) here, since the `MLmodel` is more concise, and IMO having the client cast to the right type is cleaner.

**Comment by ancasarb** [comment] 2019-06-10 12:28
👍 I'm happy with either of the two :)

**Comment by ancasarb** [comment] 2019-06-18 12:18
@dbczumar any thoughts?

**Comment by ancasarb** [comment] 2019-09-15 08:09
@dbczumar any thoughts?

**Comment by dbczumar** [comment] 2019-09-16 06:14
@ancasarb @kevinykuo Sorry for the delay here! I agree that Option 2 seems like a simpler approach that is easier for users to reason about, as compared to Option 1 which filters the training ("input") schema based on the transformer schema. I've approved #1405, pending a small change for backwards compatibility.

**Comment by dbczumar** [comment] 2019-09-17 22:14
#1405 is merged, fixing this issue. Thanks @ancasarb @kevinykuo!

**Closed by dbczumar** 2019-09-17 22:14 UTC
