### ISSUE TITLE
install mlflow with conda

### ISSUE THREAD

**Issue by Seanspt** [mlflow/mlflow#1000] opened 2019-03-14 06:38 UTC
Could mlflow be installed via conda install command?

**Comment by Seanspt** [comment] 2019-03-25 08:21
found same issue. 
[MLflow as a conda-package #400](https://github.com/mlflow/mlflow/issues/400#issue-355067323)

**Comment by mparkhe** [comment] 2019-04-05 23:25
Closing this one as duplicate of #400

**Closed by mparkhe** 2019-04-05 23:25 UTC
Labels: duplicate
