### ISSUE TITLE
[BUG] Mlflow models serve not not working on windows 8.1 

### ISSUE THREAD

**Issue by SaadAhmed96** [mlflow/mlflow#1877] opened 2019-09-25 08:14 UTC
Please fill in this template and do not delete it unless you are sure your issue is outside its scope.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in MLflow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 64 bit Windows 8.1 
- **MLflow installed from (source or binary)**: source
- **MLflow version (run ``mlflow --version``)**: 1.0
- **Python version**:  3.7
- **npm version, if running the dev UI**: 6.9.0
- **Exact command to reproduce**: (mlflow) C:\Users\Saad>mlflow models serve -m file:///D:/mlflow-master/mlflow-ma
ster/mlruns/0/c8cb103be11f4823bafab6bf86241995/artifacts/model -p 1234

### Describe the problem

I am trying to serve a model given in examples folder. I am following this [tutorial](https://mlflow.org/docs/latest/tutorial.html).  However, I am unable to serve the model. System info, command that produced the error and the error report are provided below.

### Code to reproduce the issue
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
This [tutorial ](https://mlflow.org/docs/latest/tutorial.html)can help in reproducing the problem

### Other info / logs
(mlflow) C:\Users\Saad>mlflow models serve -m file:///D:/mlflow-master/mlflow-ma
ster/mlruns/0/c8cb103be11f4823bafab6bf86241995/artifacts/model -p 1234
d:\anaconda\envs\mlflow\lib\site-packages\jinja2\utils.py:485: DeprecationWarnin
g: Using or importing the ABCs from 'collections' instead of from 'collections.a
bc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
d:\anaconda\envs\mlflow\lib\site-packages\jinja2\runtime.py:318: DeprecationWarn
ing: Using or importing the ABCs from 'collections' instead of from 'collections
.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
2019/09/25 12:42:42 INFO mlflow.models.cli: Selected backend for flavor 'python_
function'
2019/09/25 12:42:45 INFO mlflow.projects: === Creating conda environment mlflow-
684f146d22dc8c22cc480b2dfa1335663a7b1c8f ===
Warning: you have pip-installed dependencies in your environment file, but you d
o not list pip itself as one of your conda dependencies.  Conda may not use the
correct pip to install your packages, and they may end up in the wrong place.  P
lease add an explicit pip dependency.  I'm adding one for you, but still nagging
 you.
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 238,
in _load
        repodata_fn=self.repodata_fn)
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 588,
in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 1062, in __
call__
        return func(*args, **kwargs)
      File "D:\Anaconda\lib\site-packages\conda_env\cli\main.py", line 73, in do
_call
        exit_code = getattr(module, func_name)(args, parser)
      File "D:\Anaconda\lib\site-packages\conda_env\cli\main_create.py", line 10
1, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "D:\Anaconda\lib\site-packages\conda_env\installers\conda.py", line 2
7, in install
        unlink_link_transaction = solver.solve_for_transaction(prune=getattr(arg
s, 'prune', False))
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 116, in sol
ve_for_transaction
        should_retry_solve)
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 157, in sol
ve_for_diff
        force_remove, should_retry_solve)
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 261, in sol
ve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "D:\Anaconda\lib\site-packages\conda\common\io.py", line 88, in decor
ated
        return f(*args, **kwds)
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 414, in _co
llect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "D:\Anaconda\lib\site-packages\conda\core\solve.py", line 999, in _pr
epare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "D:\Anaconda\lib\site-packages\conda\core\index.py", line 214, in get
_reduced_index
        repodata_fn=repodata_fn)
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 95, i
n query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 586, in result_it
erator
        yield fs.pop().result()
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 432, in result
        return self.__get_result()
      File "D:\Anaconda\lib\concurrent\futures\_base.py", line 384, in __get_res
ult
        raise self._exception
      File "D:\Anaconda\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 88, i
n <lambda>
        package_ref_or_match_spec))
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 100,
in query
        self.load()
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 164,
in load
        _internal_state = self._load()
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 253,
in _load
        mod_etag_headers.get('_mod'))
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 301,
in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "D:\Anaconda\lib\site-packages\conda\core\subdir_data.py", line 390,
in _process_raw_repodata_str
        conda_packages = {} if context.use_only_tar_bz2 else json_obj.get("packa
ges.conda", {})
      File "D:\Anaconda\lib\site-packages\conda\base\context.py", line 664, in u
se_only_tar_bz2
        import conda_package_handling.api
      File "D:\Anaconda\lib\site-packages\conda_package_handling\api.py", line 1
2, in <module>
        from .tarball import CondaTarBZ2 as _CondaTarBZ2, libarchive_enabled
      File "D:\Anaconda\lib\site-packages\conda_package_handling\tarball.py", li
ne 11, in <module>
        import libarchive
      File "D:\Anaconda\lib\site-packages\libarchive\__init__.py", line 1, in <m
odule>
        from .entry import ArchiveEntry
      File "D:\Anaconda\lib\site-packages\libarchive\entry.py", line 6, in <modu
le>
        from . import ffi
      File "D:\Anaconda\lib\site-packages\libarchive\ffi.py", line 27, in <modul
e>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "D:\Anaconda\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "D:\Anaconda\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None

`$ D:\Anaconda\Scripts\conda-env-script.py create -n mlflow-684f146d22dc8c22cc48
0b2dfa1335663a7b1c8f --file D:\mlflow-master\mlflow-master\mlruns\0\c8cb103be11f
4823bafab6bf86241995\artifacts\model\conda.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=mlflow
                CONDA_EXE=D:\Anaconda\Scripts\conda.exe
             CONDA_PREFIX=D:\Anaconda\envs\mlflow
           CONDA_PREFIX_1=D:\Anaconda
    CONDA_PROMPT_MODIFIER=(mlflow)
         CONDA_PYTHON_EXE=D:\Anaconda\python.exe
               CONDA_ROOT=D:\Anaconda
              CONDA_SHLVL=2
         DOCKER_CERT_PATH=C:\Users\Saad\.docker\machine\machines\default
DOCKER_TOOLBOX_INSTALL_PATH=D:\Docker Toolbox
                 HOMEPATH=\Users\Saad
                 NO_PROXY=<set>
                     PATH=D:\Anaconda\envs\mlflow;D:\Anaconda\envs\mlflow\Librar
y\mingw-w64\bin;
                          D:\Anaconda\envs\mlflow\Library\usr\bin;D:\Anaconda\en
vs\mlflow\Librar
                          y\bin;D:\Anaconda\envs\mlflow\Scripts;D:\Anaconda\envs
\mlflow\bin;D:\A
                          naconda\condabin;C:\Program Files (x86)\Intel\iCLS Cli
ent;C:\Program
                          Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS
;C:\WINDOWS\Syst
                          em32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C
:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;
C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;
C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;
C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;
D:\MATLAB\bin;D:
                          \JS;D:\Git\cmd;C:\Users\Saad\AppData\Local\Programs\Py
thon\Python36\Sc
                          ripts;C:\Users\Saad\AppData\Local\Programs\Python\Pyth
on36;C:\Users\Sa
                          ad\AppData\Roaming\npm;D:\BioVinci;D:\Docker
                          Toolbox;D:\Anaconda\lib\site-
                          packages\pywin32_system32;D:\Anaconda\lib\site-
                          packages\pywin32_system32;d:\anaconda\envs\mlflow\lib\
site-
                          packages\pywin32_system32;d:\anaconda\envs\mlflow\lib\
site-
                          packages\numpy\.libs;D:\Anaconda\lib\site-
                          packages\pywin32_system32;D:\Anaconda\lib\site-
                          packages\pywin32_system32
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : mlflow
    active env location : D:\Anaconda\envs\mlflow
            shell level : 2
       user config file : C:\Users\Saad\.condarc
 populated config files : C:\Users\Saad\.condarc
          conda version : 4.7.11
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       virtual packages :
       base environment : D:\Anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\Saad\.conda\pkgs
                          C:\Users\Saad\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\Saad\.conda\envs
                          C:\Users\Saad\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.1 Windows/8.1
 Windows/6.3.9600
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
Timeout reached. No report sent.

Traceback (most recent call last):
  File "d:\anaconda\envs\mlflow\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\envs\mlflow\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\mlflow\Scripts\mlflow.exe\__main__.py", line 9, in <mod
ule>
  File "d:\anaconda\envs\mlflow\lib\site-packages\click\core.py", line 764, in _
_call__
    return self.main(*args, **kwargs)
  File "d:\anaconda\envs\mlflow\lib\site-packages\click\core.py", line 717, in m
ain
    rv = self.invoke(ctx)
  File "d:\anaconda\envs\mlflow\lib\site-packages\click\core.py", line 1137, in
invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda\envs\mlflow\lib\site-packages\click\core.py", line 1137, in
invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\anaconda\envs\mlflow\lib\site-packages\click\core.py", line 956, in i
nvoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\anaconda\envs\mlflow\lib\site-packages\click\core.py", line 555, in i
nvoke
    return callback(*args, **kwargs)
  File "d:\anaconda\envs\mlflow\lib\site-packages\mlflow\models\cli.py", line 56
, in serve
    host=host)
  File "d:\anaconda\envs\mlflow\lib\site-packages\mlflow\pyfunc\backend.py", lin
e 77, in serve
    command_env=command_env)
  File "d:\anaconda\envs\mlflow\lib\site-packages\mlflow\pyfunc\backend.py", lin
e 130, in _execute_in_conda_env
    conda_env_name = _get_or_create_conda_env(conda_env_path, env_id=env_id)
  File "d:\anaconda\envs\mlflow\lib\site-packages\mlflow\projects\__init__.py",
line 498, in _get_or_create_conda_env
    conda_env_path], stream_output=True)
  File "d:\anaconda\envs\mlflow\lib\site-packages\mlflow\utils\process.py", line
 38, in exec_cmd
    raise ShellCommandException("Non-zero exitcode: %s" % (exit_code))
mlflow.utils.process.ShellCommandException: Non-zero exitcode: 1

**Comment by tomasatdatabricks** [comment] 2019-09-30 23:53
Hi @SaadAhmed96, thanks for posting! The mlflow models serve is unfortunately not supported on Windows at the moment. Windows support is currently limited to tracking, we would appreciate contributions in this direction though!

In the meantime, you may try to build the model into a docker image instead via ``mlflow models build-docker`` command. 

I am gonna close this as this is not a bug, fell free to resubmit this as an enhancement.

**Closed by tomasatdatabricks** 2019-09-30 23:53 UTC
Labels: bug
