### ISSUE TITLE
Getting 401 error despite setting MLFLOW_TRACKING_TOKEN

### ISSUE THREAD

**Issue by ravitejapagala** [mlflow/mlflow#11036] opened 2024-02-06 11:10 UTC
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

Yes. I can contribute a fix for this bug independently.

### MLflow version

mlflow==2.10.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Python version**:
- **yarn version, if running the dev UI**:

### Issue Description
I am encountering a 401 error while trying to fetch data using the Python `requests` module, despite setting the `MLFLOW_TRACKING_TOKEN` environment variable. 

### Steps to Replicate
1. Run MLflow inside a Docker container.
2. exec into the container.
3. export `MLFLOW_TRACKING_TOKEN=<random_string>`.
4. Run the Python script provided below:

```python
import requests
response = requests.get(r'http://<tracking_uri:5000/api/2.0/mlflow/experiments/search', json={"max_results":10}, headers={"Authorization":f"Bearer <random_string>"})
print(response)
```

### Tracking information

Able to read from the environment file, but encountering a 401 error when attempting to authenticate using requests module it is throwing an 401 error.
**environment_variables.py file**
MLFLOW_TRACKING_TOKEN = _EnvironmentVariable("MLFLOW_TRACKING_TOKEN", str, None)

### Code to reproduce issue

**Outside of the docker container:**
```python
import requests
response = requests.get(r'http://<tracking_uri:5000/api/2.0/mlflow/experiments/search',json={"max_results":10},headers={"Authorization":f"Bearer <random_string>"})
print(response)
```

### Stack trace

You are not authenticated. Please see https://www.mlflow.org/docs/latest/auth/index.html#authenticating-to-mlflow on how to authenticate.

### Additional Information:
I have referred to the MLflow documentation https://mlflow.org/docs/latest/tracking/server.html

I removed the MLFLOW_TRACKING_USERNAME and MLFLOW_TRACKING_PASSWORD environment variables and exported the MLFLOW_TRACKING_TOKEN=<random_string>.
According to the documentation, MLFLOW_TRACKING_USERNAME and MLFLOW_TRACKING_PASSWORD are used for HTTP Basic authentication, but I'm using Bearer authentication with the token.

### Other info / logs

You are not authenticated. Please see https://www.mlflow.org/docs/latest/auth/index.html#authenticating-to-mlflow on how to authenticate.

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [X] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [X] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by BenWilson2** [comment] 2024-02-07 22:19
Are you able to connect using basic username and password with changing nothing else about your container configuration? cc @gabrielfu

**Comment by gabrielfu** [comment] 2024-02-08 03:35
If you would like to enable token-based authentication, you should configure `authorization_function` field in the [auth config](authorization_function). Setting `MLFLOW_TRACKING_TOKEN` on the server (docker container) does nothing.

If you did not configure the above, MLflow server expects basic auth. Your request is using bearer token and thus is undetected by MLflow server.

**Comment by gabrielfu** [comment] 2024-02-19 06:05
Closing this as not a bug. @ravitejapagala feel free to reopen if you encounter further issues

**Closed by gabrielfu** 2024-02-19 06:05 UTC
Labels: bug, area/uiux, area/docker, language/new
