### ISSUE TITLE
[BUG] MLflow Pipelines fails if space found in the repository Path (make: *** No rule to make target)

### ISSUE THREAD

**Issue by OSobky** [mlflow/mlflow#6404] opened 2022-08-04 13:26 UTC
### Willingness to contribute

Yes. I would be willing to contribute a fix for this bug with guidance from the MLflow community.

### MLflow version

1.27.0

### System information

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Python version**: 3.7.13
- **yarn version, if running the dev UI**:

### Describe the problem

I was following the instruction on the [Regression Pipeline repository](https://github.com/mlflow/mlp-regression-template), where I cloned the repo in a folder called **MLflow Pipelines**. However, I got an error when I was trying to run `p.run("split")` cell in [jupyter.ipynb](https://github.com/mlflow/mlp-regression-template/blob/main/notebooks/jupyter.ipynb) notebook. The error:
`make: *** No rule to make target 'steps/split/outputs/train.parquet', needed by 'split'.  Stop.`

### Code to reproduce issue

Run the  [jupyter.ipynb](https://github.com/mlflow/mlp-regression-template/blob/main/notebooks/jupyter.ipynb) notebook after cloning the repo in a folder with space in it 

### Stack trace

make: *** No rule to make target 'steps/split/outputs/train.parquet', needed by 'split'.  Stop.

### Other info / logs

After some debugging, I found the problem in the **Makefile** created for the pipeline as it is space sensitive 

### What component(s) does this bug affect?

- [ ] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [X] `area/pipelines`: Pipelines, Pipeline APIs, Pipeline configs, Pipeline Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [ ] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

### What language(s) does this bug affect?

- [ ] `language/r`: R APIs and clients
- [ ] `language/java`: Java APIs and clients
- [ ] `language/new`: Proposals for new client languages

### What integration(s) does this bug affect?

- [ ] `integrations/azure`: Azure and Azure ML integrations
- [ ] `integrations/sagemaker`: SageMaker integrations
- [ ] `integrations/databricks`: Databricks integrations

**Comment by dbczumar** [comment] 2022-08-05 00:13
@OSobky Thank you for your report. Can you confirm that the pipeline runs properly after renaming the directory so that it no longer includes a space? I'd like to make sure that the space is the root cause :)

**Comment by OSobky** [comment] 2022-08-06 07:15
@dbczumar yes, I confirm I was able to run the pipeline after renaming the directory name :)

**Comment by dbczumar** [comment] 2022-08-08 02:27
Awesome, thanks @OSobky. We're investigating :)

**Comment by dbczumar** [comment] 2022-08-09 16:58
@OSobky Unfortunately, after significant investigation, it appears that most Make implementations, such as GNU Make (e.g. https://savannah.gnu.org/bugs/?712), do not support file paths with spaces. Because MLflow Pipelines uses Make for execution caching, it is difficult for us to support paths with spaces at this time. I have introduced https://github.com/mlflow/mlflow/pull/6426 to raise a much clearer error message for this case. Thank you for bringing this to our attention!

**Comment by dbczumar** [comment] 2022-08-10 04:49
Closing now that https://github.com/mlflow/mlflow/pull/6426 has been merged :)

**Closed by dbczumar** 2022-08-10 04:49 UTC
Labels: bug, area/pipelines
