### ISSUE TITLE
[BUG] Error reading/loading artifact image.

### ISSUE THREAD

**Issue by JohnConnor123** [mlflow/mlflow#13014] opened 2024-08-28 00:50 UTC
### Issues Policy acknowledgement

- [X] I have read and agree to submit bug reports in accordance with the [issues policy](https://www.github.com/mlflow/mlflow/blob/master/ISSUE_POLICY.md)

### Where did you encounter this bug?

Local machine

### Willingness to contribute

No. I cannot contribute a bug fix at this time.

### MLflow version

version 2.15.1

### System information

- Windows 10 Pro 22H2, Version 10.0.19045 build 19045
- Python 3.12

### Describe the problem

I saved images while training the model. An error occurs when viewing artifacts. The mlflow server console says the image was not found. The name of the image is incorrect - the "%" signs are missing (for example, after the word timestamp in the file name), and the timestamp value itself in mlflow server ui and in the directory are different (although the photos are the same, because step from the file name is zero).

Code to reproduce: https://github.com/JohnConnor123/mlops-example/tree/mlflow-version

MLflow ui image path and name:
![image](https://github.com/user-attachments/assets/3f1a4a8a-8ac3-42f0-a74b-10bff26e6ab8)

Result of clicking on image file in mlflow ui:
![image](https://github.com/user-attachments/assets/110d7606-a0fb-4f59-ab8c-d23088d9a042)

Image name in folder:
![image](https://github.com/user-attachments/assets/5f17768d-069b-4fde-98b3-fedfa48bd1db)

MLflow server output from git bash console:
![image](https://github.com/user-attachments/assets/5e92afe4-ae96-407f-ba8e-effaf5c1d108)

### Code to reproduce issue

```
git clone https://github.com/JohnConnor123/mlops-example/tree/mlflow-version
cd mlops-example
poetry install
cd mlflow-medical-segmentation
poetry shell
python main.py
```

### Stack trace

After executing this:
```
export MLFLOW_REGISTRY_URI=mlflow-medical-segmentation/logs/mlflow-registry

mlflow server --host localhost --port 5000 --backend-store-uri sqlite:///${MLFLOW_REGISTRY_URI}/mlflow.db --default-artifact-root ${MLFLOW_REGISTRY_URI}
```
Output in git bash console when clicking on image in mlflow server UI:
```
Traceback (most recent call last):
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\mlflow\server\__init__.py", line 74, in serve_artifacts
    return get_artifact_handler()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\mlflow\server\handlers.py", line 566, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\mlflow\server\handlers.py", line 633, in get_artifact_handler
    return _send_artifact(artifact_repo, artifact_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\mlflow\server\handlers.py", line 554, in _send_artifact
    file_path = os.path.abspath(artifact_repository.download_artifacts(path))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John\AppData\Local\pypoetry\Cache\virtualenvs\mlflow-medical-segmentation-szZH9KnF-py3.12\Lib\site-packages\mlflow\store\artifact\local_artifact_repo.py", line 91, in download_artifacts
    raise OSError(f"No such file or directory: '{local_artifact_path}'")
OSError: No such file or directory: 'D:\Python_Projects\Jupyter\MLOps\mlflow-medical-segmentation\mlflow-medical-segmentation\logs\mlflow-registry\1\0142c59089ca41e180d55f8f4486f8e4\artifacts\images\Predictions at val_loader%step%0%timestamp24764613273\ufffd117463-53dc-4dd2-8a06-a22418612f40.png'

```

### What component(s) does this bug affect?

- [X] `area/artifacts`: Artifact stores and artifact logging
- [ ] `area/build`: Build and test infrastructure for MLflow
- [ ] `area/deployments`: MLflow Deployments client APIs, server, and third-party Deployments integrations
- [ ] `area/docs`: MLflow documentation pages
- [ ] `area/examples`: Example code
- [ ] `area/model-registry`: Model Registry service, APIs, and the fluent client calls for Model Registry
- [ ] `area/models`: MLmodel format, model serialization/deserialization, flavors
- [ ] `area/recipes`: Recipes, Recipe APIs, Recipe configs, Recipe Templates
- [ ] `area/projects`: MLproject format, project running backends
- [ ] `area/scoring`: MLflow Model server, model deployment tools, Spark UDFs
- [ ] `area/server-infra`: MLflow Tracking server backend
- [ ] `area/tracking`: Tracking Service, tracking client APIs, autologging

### What interface(s) does this bug affect?

- [X] `area/uiux`: Front-end, user experience, plotting, JavaScript, JavaScript dev server
- [ ] `area/docker`: Docker use across MLflow's components, such as MLflow Projects and MLflow Models
- [ ] `area/sqlalchemy`: Use of SQLAlchemy in the Tracking Service or Model Registry
- [ ] `area/windows`: Windows support

**Comment by aknoerig** [comment] 2024-08-28 12:10
Duplicate of #12151 ?

**Comment by JohnConnor123** [comment] 2024-08-29 11:01
> Duplicate of #12151 ?

Not really. In my case, in addition to the incorrect display of "%", the timestamp is incorrectly displayed. And traceback is different.

**Comment by harupy** [comment] 2024-08-31 00:00
This is a duplicate of #12151.

**Closed by harupy** 2024-08-31 00:00 UTC
Labels: bug, area/uiux, area/artifacts

**Comment by harupy** [comment] 2024-08-31 00:15
> the timestamp is incorrectly displayed

This is because `%` and the first two digits in the timestamp value are converted to a different character.
